export type LoanOfferStatus = "active" | "standard" | "verify";

export type LoanOffer = {
  id: string;
  bank: string;
  mark: string;
  product: string;
  rate: string;
  rateValue: number;
  fee: string;
  feeValue: number;
  apr: string;
  aprValue: number;
  monthly: string;
  maxAmount: string;
  maxTerm: string;
  audience: string;
  tags: string[];
  status: LoanOfferStatus;
  analysis: string[];
  qualification: string[];
  cautions: string[];
  officialUrl: string;
};

export const loanComparisonUpdatedAt = "2026-07-03";
export const loanComparisonReferenceUrl =
  "https://www.money101.com.tw/%E8%B2%B8%E6%AC%BE/%E4%BF%A1%E7%94%A8%E8%B2%B8%E6%AC%BE";

export const loanOffers: LoanOffer[] = [
  {
    id: "fubon-personal",
    bank: "台北富邦",
    mark: "富",
    product: "個人信用貸款",
    rate: "0.01% 起",
    rateValue: 0.01,
    fee: "NT$0 起",
    feeValue: 0,
    apr: "2.71% 起",
    aprValue: 2.71,
    monthly: "NT$3,811 起",
    maxAmount: "NT$800 萬",
    maxTerm: "最長 7 年",
    audience: "年滿 18 歲、年收入 30 萬元以上者",
    tags: ["精選", "線上申辦"],
    status: "active",
    analysis: ["首期優惠利率搭配零手續費條件。", "可線上完成申請，並支援數位財力資料驗證。", "額度最高 800 萬元，實際核准依個人條件。"],
    qualification: ["最低年齡參考為 18 歲。", "年收入門檻參考為 30 萬元。", "銀行會依信用、收入與負債狀況審核。"],
    cautions: ["第二期起利率與提前清償條件須看正式契約。", "優惠通路與活動期限可能限制適用資格。"],
    officialUrl: "https://www.fubon.com/banking/Personal/loan/index.htm",
  },
  {
    id: "sinopac-digital",
    bank: "永豐銀行",
    mark: "永",
    product: "永豐數時貸",
    rate: "0.01% 起",
    rateValue: 0.01,
    fee: "NT$0 起",
    feeValue: 0,
    apr: "2.58% 起",
    aprValue: 2.58,
    monthly: "NT$3,811 起",
    maxAmount: "NT$800 萬",
    maxTerm: "最長 84 期",
    audience: "18–60 歲、年收入 30 萬元以上的一般受薪族",
    tags: ["精選", "線上申辦"],
    status: "active",
    analysis: ["首期利率與手續費設有優惠門檻。", "線上簽約後可快速完成撥款流程。", "最高額度 800 萬元，貸款期間最長 84 期。"],
    qualification: ["年齡參考區間為 18–60 歲。", "年收入參考門檻為 30 萬元。", "自營商、自由業等身份須另看銀行規定。"],
    cautions: ["零手續費可能與限制清償期間綁定。", "機動利率會隨指標調整。"],
    officialUrl: "https://bank.sinopac.com/sinopacBT/webevents/psn_loan/index.html",
  },
  {
    id: "kgi-step-rate",
    bank: "凱基銀行",
    mark: "凱",
    product: "階段式優惠信貸",
    rate: "0.01% 起",
    rateValue: 0.01,
    fee: "NT$0 起",
    feeValue: 0,
    apr: "3.17% 起",
    aprValue: 3.17,
    monthly: "NT$3,811 起",
    maxAmount: "NT$1,000 萬",
    maxTerm: "最長 10 年",
    audience: "18–60 歲、年收入 30 萬元以上者",
    tags: ["高額度", "長年期"],
    status: "active",
    analysis: ["首月優惠利率，第二期起依核定利率計算。", "額度最高 1,000 萬元、年期最長 10 年。", "開辦費會隨限制清償期長度調整。"],
    qualification: ["年齡參考區間為 18–60 歲。", "年收入參考門檻為 30 萬元。", "須為本國國民並通過銀行授信審核。"],
    cautions: ["優惠利率不是全期固定利率。", "零開辦費通常需要較長綁約期。"],
    officialUrl: "https://www.kgibank.com.tw/",
  },
  {
    id: "dbs-personal",
    bank: "星展銀行",
    mark: "星",
    product: "個人信貸",
    rate: "0.01% 起",
    rateValue: 0.01,
    fee: "NT$0 起",
    feeValue: 0,
    apr: "3.79% 起",
    aprValue: 3.79,
    monthly: "NT$3,811 起",
    maxAmount: "NT$500 萬",
    maxTerm: "最長 10 年",
    audience: "20–63 歲、有穩定收入與正常信用紀錄者",
    tags: ["長年期", "線上申辦"],
    status: "active",
    analysis: ["提供首期優惠利率與線上申辦流程。", "可透過 MyData 簡化財力資料提供。", "最高額度 500 萬元，最長可分 10 年。"],
    qualification: ["最低年齡參考為 20 歲。", "需有穩定收入與正常信用紀錄。", "持有信用卡且具半年以上工作年資者較符合一般條件。"],
    cautions: ["提前清償可能產生違約金。", "實際利率、額度與撥款速度依個案核定。"],
    officialUrl: "https://www.dbs.com.tw/personal-zh/loans/personal-loan/default.page",
  },
  {
    id: "hsbc-personal",
    bank: "滙豐銀行",
    mark: "滙",
    product: "個人信用貸款",
    rate: "0.01% 起",
    rateValue: 0.01,
    fee: "NT$0 起",
    feeValue: 0,
    apr: "2.46% 起",
    aprValue: 2.46,
    monthly: "NT$3,811 起",
    maxAmount: "NT$800 萬",
    maxTerm: "最長 7 年",
    audience: "18–55 歲、月收入 5 萬元以上且持卡滿半年者",
    tags: ["精選", "線上申辦"],
    status: "active",
    analysis: ["首期優惠利率，第二期起採機動利率。", "線上申請可免列印與郵寄文件。", "最高額度 800 萬元，最長 7 年。"],
    qualification: ["年齡參考區間為 18–55 歲。", "月收入參考門檻為 5 萬元。", "需持有任一家銀行信用卡滿 6 個月。"],
    cautions: ["綁約與不綁約方案的費用、APR 不同。", "收入文件與適用身份以銀行最新規定為準。"],
    officialUrl: "https://www.hsbc.com.tw/loans/",
  },
  {
    id: "ctbc-online",
    bank: "中國信託",
    mark: "中",
    product: "Online 貸",
    rate: "0.01% 起",
    rateValue: 0.01,
    fee: "NT$3,000 起",
    feeValue: 3000,
    apr: "3.30% 起",
    aprValue: 3.3,
    monthly: "NT$3,811 起",
    maxAmount: "NT$800 萬",
    maxTerm: "最長 7 年",
    audience: "年滿 18 歲、年收入 30 萬元以上者",
    tags: ["線上申辦"],
    status: "active",
    analysis: ["首期固定優惠利率，第二期起採機動計息。", "開辦費 3,000 元起。", "最高額度 800 萬元、最長 7 年。"],
    qualification: ["最低年齡參考為 18 歲。", "年收入參考門檻為 30 萬元。", "部分身份驗證流程可減少文件上傳。"],
    cautions: ["首期低利率不代表全期成本。", "總費用年百分率與提前清償條件須一併比較。"],
    officialUrl: "https://www.ctbcbank.com/",
  },
  {
    id: "standard-chartered-personal",
    bank: "渣打銀行",
    mark: "渣",
    product: "個人信用貸款",
    rate: "0.01% 起",
    rateValue: 0.01,
    fee: "NT$0 起",
    feeValue: 0,
    apr: "2.59% 起",
    aprValue: 2.59,
    monthly: "NT$3,811 起",
    maxAmount: "NT$600 萬",
    maxTerm: "依核定條件",
    audience: "20 歲以上、年收入 30 萬元以上者",
    tags: ["線上申辦"],
    status: "verify",
    analysis: ["頁面展示首期優惠利率與零帳管費條件。", "最高額度參考為 600 萬元。", "支援 24 小時線上申辦與 MyData 財力驗證。"],
    qualification: ["最低年齡參考為 20 歲。", "年收入參考門檻為 30 萬元。", "部分優惠僅適用全新信貸客戶。"],
    cautions: ["參考頁中的活動申請期限已過，申請前必須回銀行官網重查。", "限制清償期間可能長達 36 個月。"],
    officialUrl: "https://www.sc.com/tw/personal-loan/",
  },
  {
    id: "taishin-richart",
    bank: "台新銀行",
    mark: "台",
    product: "Richart 信貸",
    rate: "2.10% 起",
    rateValue: 2.1,
    fee: "NT$0 起",
    feeValue: 0,
    apr: "2.10% 起",
    aprValue: 2.1,
    monthly: "NT$4,100 起",
    maxAmount: "NT$500 萬",
    maxTerm: "依核定條件",
    audience: "20–60 歲、符合 Richart 線上申辦條件者",
    tags: ["一段式", "線上申辦"],
    status: "verify",
    analysis: ["主打一段式機動利率。", "新戶手續費可依活動條件減免。", "可透過 Richart 官網完成線上申請。"],
    qualification: ["年齡參考區間為 20–60 歲。", "部分活動限未持有 Richart 帳戶且未申辦過台新信貸者。", "額度與利率仍依個人條件核定。"],
    cautions: ["參考頁展開內容仍保留 2025 年活動日期，需以銀行官網為準。", "零手續費可能與 60 期限制清償條件綁定。"],
    officialUrl: "https://richart.tw/",
  },
  {
    id: "obank-standard",
    bank: "王道銀行",
    mark: "王",
    product: "信貸優惠方案",
    rate: "2.35% 起",
    rateValue: 2.35,
    fee: "NT$0 起",
    feeValue: 0,
    apr: "2.35% 起",
    aprValue: 2.35,
    monthly: "NT$4,135 起",
    maxAmount: "NT$500 萬",
    maxTerm: "最長 7 年",
    audience: "18–65 歲、有固定收入且年收入 24 萬元以上者",
    tags: ["一段式"],
    status: "standard",
    analysis: ["一段式機動利率，利率結構較容易理解。", "最高額度 500 萬元、最長 7 年。", "頁面試算條件下手續費為 0 元。"],
    qualification: ["年齡參考區間為 18–65 歲。", "年收入參考門檻為 24 萬元。", "需具固定收入且無重大信用異常。"],
    cautions: ["零費用可能搭配限制清償期。", "機動利率會隨定儲利率指數調整。"],
    officialUrl: "https://www.o-bank.com/",
  },
  {
    id: "feib-online",
    bank: "遠東商銀",
    mark: "遠",
    product: "Online 貸",
    rate: "2.38% 起",
    rateValue: 2.38,
    fee: "依專案而定",
    feeValue: 2588,
    apr: "2.74% 起",
    aprValue: 2.74,
    monthly: "NT$4,139 起",
    maxAmount: "NT$700 萬",
    maxTerm: "最長 8 年",
    audience: "年滿 18 歲、年收入 25 萬元以上者",
    tags: ["線上申辦", "長年期"],
    status: "verify",
    analysis: ["提供一段式機動利率方案。", "最高額度參考為 700 萬元。", "開辦費會隨專案與限制清償期調整。"],
    qualification: ["最低年齡參考為 18 歲。", "年收入參考門檻為 25 萬元。", "實際文件與收入認定由銀行審核。"],
    cautions: ["參考頁列出的活動期限已於 2026-06-30 結束。", "卡片摘要與展開條款的最長年期不一致，須回官網確認。"],
    officialUrl: "https://www.feib.com.tw/",
  },
  {
    id: "rakuten-installment",
    bank: "樂天國際銀行",
    mark: "樂",
    product: "樂天貸（分期型）",
    rate: "2.12% 起",
    rateValue: 2.12,
    fee: "NT$0 起",
    feeValue: 0,
    apr: "2.12% 起",
    aprValue: 2.12,
    monthly: "NT$4,375 起",
    maxAmount: "NT$500 萬",
    maxTerm: "依核定條件",
    audience: "年滿 18 歲並符合樂天銀行授信條件者",
    tags: ["一段式", "線上申辦"],
    status: "active",
    analysis: ["一段式機動利率，費率結構較直觀。", "活動條件下可免開辦費。", "最高額度 500 萬元，可線上申貸。"],
    qualification: ["最低年齡參考為 18 歲。", "未在比較頁標示固定年薪門檻。", "仍須依銀行徵審結果決定額度與利率。"],
    cautions: ["免開辦費有活動期限。", "總費用年百分率不等於名目貸款利率。"],
    officialUrl: "https://www.rakuten-bank.com.tw/",
  },
  {
    id: "kgi-flat-rate",
    bank: "凱基銀行",
    mark: "凱",
    product: "一段式低利率信貸",
    rate: "2.88% 起",
    rateValue: 2.88,
    fee: "NT$0 起",
    feeValue: 0,
    apr: "2.88% 起",
    aprValue: 2.88,
    monthly: "NT$4,211 起",
    maxAmount: "NT$1,000 萬",
    maxTerm: "最長 10 年",
    audience: "18–60 歲、年收入 30 萬元以上者",
    tags: ["一段式", "高額度", "長年期"],
    status: "active",
    analysis: ["一段式機動利率，便於估算整體成本。", "額度最高 1,000 萬元、年期最長 10 年。", "開辦費依限制清償期長度分級。"],
    qualification: ["年齡參考區間為 18–60 歲。", "年收入參考門檻為 30 萬元。", "需為本國國民。"],
    cautions: ["零開辦費通常需選擇較長限制清償期。", "提前還款前應先確認違約金。"],
    officialUrl: "https://www.kgibank.com.tw/",
  },
  {
    id: "kgi-revolving",
    bank: "凱基銀行",
    mark: "凱",
    product: "速還金（循環型）",
    rate: "0.01% 起",
    rateValue: 0.01,
    fee: "NT$0 起",
    feeValue: 0,
    apr: "3.50% 起",
    aprValue: 3.5,
    monthly: "按實際動用計息",
    maxAmount: "NT$100 萬",
    maxTerm: "循環額度",
    audience: "18–60 歲、入職滿一個月的上班族或自由業者",
    tags: ["循環型", "彈性動用"],
    status: "verify",
    analysis: ["額度核准後可按需動用，有動用才計息。", "最高額度參考為 100 萬元。", "可隨借隨還，提前還款通常不收違約金。"],
    qualification: ["年齡參考區間為 18–60 歲。", "上班族與自由業者皆可依條件申請。", "核定利率依個人信用條件。"],
    cautions: ["參考頁列出的開辦費優惠期限已過。", "每次動用可能收帳務管理費，需比較實際使用頻率。"],
    officialUrl: "https://www.kgibank.com.tw/",
  },
  {
    id: "ctbc-small",
    bank: "中國信託",
    mark: "中",
    product: "小額分期信貸",
    rate: "0.01% 起",
    rateValue: 0.01,
    fee: "NT$3,000 起",
    feeValue: 3000,
    apr: "3.30% 起",
    aprValue: 3.3,
    monthly: "NT$3,811 起",
    maxAmount: "NT$800 萬",
    maxTerm: "最長 7 年",
    audience: "年滿 18 歲、年收入 30 萬元以上者",
    tags: ["小額", "線上申辦"],
    status: "active",
    analysis: ["首期固定優惠利率，第二期起採機動計息。", "小額需求可依貸款金額適用不同開辦費。", "最高額度與期間仍由銀行核定。"],
    qualification: ["最低年齡參考為 18 歲。", "年收入參考門檻為 30 萬元。", "需通過銀行身分、收入與信用審核。"],
    cautions: ["不要只比較首期利率，應看 APR 與總還款額。", "小額貸款的固定費用占比可能更高。"],
    officialUrl: "https://www.ctbcbank.com/",
  },
  {
    id: "ctbc-existing",
    bank: "中國信託",
    mark: "中",
    product: "信貸舊戶貸款",
    rate: "0.01% 起",
    rateValue: 0.01,
    fee: "NT$7,000 起",
    feeValue: 7000,
    apr: "3.85% 起",
    aprValue: 3.85,
    monthly: "NT$3,811 起",
    maxAmount: "NT$800 萬",
    maxTerm: "最長 7 年",
    audience: "中國信託既有信貸餘額客戶",
    tags: ["舊戶", "快速撥款"],
    status: "verify",
    analysis: ["限既有信貸客戶申請。", "可依資金活用或債務整合目的選擇方案。", "營業時間內可能加快撥款流程。"],
    qualification: ["需為中國信託信貸既有客戶。", "年收入參考門檻為 30 萬元。", "仍須重新進行授信評估。"],
    cautions: ["參考頁中的優惠申請期限已過。", "不同用途的開辦費與利率可能不同。"],
    officialUrl: "https://www.ctbcbank.com/",
  },
  {
    id: "ctbc-payroll",
    bank: "中國信託",
    mark: "中",
    product: "薪轉戶專屬信貸",
    rate: "0.01% 起",
    rateValue: 0.01,
    fee: "NT$7,000 起",
    feeValue: 7000,
    apr: "3.85% 起",
    aprValue: 3.85,
    monthly: "NT$3,811 起",
    maxAmount: "NT$800 萬",
    maxTerm: "最長 7 年",
    audience: "中國信託薪資轉帳戶",
    tags: ["薪轉戶", "文件簡化"],
    status: "verify",
    analysis: ["限中國信託薪轉戶申請。", "銀行可依既有撥薪紀錄認定部分收入資料。", "小額貸款可能適用不同開辦費級距。"],
    qualification: ["需有中國信託薪轉紀錄。", "年收入參考門檻為 30 萬元。", "銀行仍可能要求補充文件。"],
    cautions: ["參考頁中的優惠申請期限已過。", "首期利率、後續利率與總費用須分開查看。"],
    officialUrl: "https://www.ctbcbank.com/",
  },
  {
    id: "ctbc-sme",
    bank: "中國信託",
    mark: "中",
    product: "中小企業貸款",
    rate: "3.00% 起",
    rateValue: 3,
    fee: "依個案核定",
    feeValue: 99999,
    apr: "4.68% 起",
    aprValue: 4.68,
    monthly: "依個案試算",
    maxAmount: "NT$1,000 萬",
    maxTerm: "最長 5 年",
    audience: "成立滿一年、符合信保基金定義的中小企業",
    tags: ["企業貸款", "高額度"],
    status: "verify",
    analysis: ["提供中小企業營運資金需求評估。", "最高額度參考為 1,000 萬元。", "可預約銀行專人進一步核對企業資料。"],
    qualification: ["企業成立滿一年。", "參考頁列示年營收 100 萬至 1 億元且稅前淨利為正。", "企業與關係人票債信須正常。"],
    cautions: ["參考頁列示的活動期間已過。", "企業貸款不是一般個人信貸，審核資料與費用差異較大。"],
    officialUrl: "https://www.ctbcbank.com/",
  },
  {
    id: "bankee-challenge",
    bank: "遠東商銀",
    mark: "遠",
    product: "Bankee 挑戰型信貸",
    rate: "4.00% 起",
    rateValue: 4,
    fee: "NT$8,888",
    feeValue: 8888,
    apr: "5.23% 起",
    aprValue: 5.23,
    monthly: "NT$4,374 起",
    maxAmount: "NT$700 萬",
    maxTerm: "最長 7 年",
    audience: "持有 Bankee 數位存款帳戶並符合線上申貸條件者",
    tags: ["回饋型", "線上申辦"],
    status: "verify",
    analysis: ["設計為按時足額扣款後再判斷回饋資格。", "最高額度參考為 700 萬元。", "需要搭配 Bankee 數位存款帳戶。"],
    qualification: ["需選擇指定線上與綁約流程。", "須持有可正常交易的 Bankee 帳戶。", "實際收入與信用條件由銀行審核。"],
    cautions: ["參考頁列出的專案期間已過。", "回饋不等於利率減半，且需符合完整繳款與帳戶條件。"],
    officialUrl: "https://www.feib.com.tw/",
  },
  {
    id: "obank-consolidation",
    bank: "王道銀行",
    mark: "王",
    product: "債務整合信貸",
    rate: "3.49% 起",
    rateValue: 3.49,
    fee: "NT$9,000",
    feeValue: 9000,
    apr: "4.73% 起",
    aprValue: 4.73,
    monthly: "NT$4,299 起",
    maxAmount: "NT$500 萬",
    maxTerm: "依核定條件",
    audience: "18–65 歲、有固定收入且有整合他行債務需求者",
    tags: ["債務整合"],
    status: "standard",
    analysis: ["用於整合他行信貸或卡債，降低帳務分散。", "最高額度參考為 500 萬元。", "是否能降低月付仍要依核定利率與年期試算。"],
    qualification: ["年齡參考區間為 18–65 歲。", "年收入參考門檻為 24 萬元。", "需有固定收入並通過債務與信用評估。"],
    cautions: ["整合後拉長年期可能降低月付但增加總利息。", "限制清償期內提前還款可能有違約金。"],
    officialUrl: "https://www.o-bank.com/",
  },
  {
    id: "obank-step",
    bank: "王道銀行",
    mark: "王",
    product: "階梯利率信貸",
    rate: "0.07% 起",
    rateValue: 0.07,
    fee: "NT$8,800 起",
    feeValue: 8800,
    apr: "4.99% 起",
    aprValue: 4.99,
    monthly: "NT$3,819 起",
    maxAmount: "NT$500 萬",
    maxTerm: "最長 7 年",
    audience: "18–65 歲、有固定收入且年收入 24 萬元以上者",
    tags: ["階段式"],
    status: "standard",
    analysis: ["首期固定優惠利率，第二期起採機動利率。", "最高額度 500 萬元、最長 84 期。", "適合願意同時比較首期與後續成本的人。"],
    qualification: ["年齡參考區間為 18–65 歲。", "年收入參考門檻為 24 萬元。", "需有固定收入且無信用不良紀錄。"],
    cautions: ["首期利率很低，但 APR 反映的整體成本較高。", "提前清償可能有違約金。"],
    officialUrl: "https://www.o-bank.com/",
  },
  {
    id: "obank-professional",
    bank: "王道銀行",
    mark: "王",
    product: "優質客戶貸款",
    rate: "3.31% 起",
    rateValue: 3.31,
    fee: "NT$7,000",
    feeValue: 7000,
    apr: "4.28% 起",
    aprValue: 4.28,
    monthly: "NT$4,273 起",
    maxAmount: "依核定條件",
    maxTerm: "依核定條件",
    audience: "特定專業人士、金融業主管或績優企業高階主管",
    tags: ["專業人士"],
    status: "verify",
    analysis: ["鎖定特定專業證照人士與高階主管。", "採一段式機動利率。", "身份認定以銀行徵審結果為準。"],
    qualification: ["參考身份包括律師、會計師、建築師、法醫與醫師。", "部分金融同業主管與績優企業高階主管也可評估。", "需有固定收入。"],
    cautions: ["參考頁的計算基準日期出现不一致，須回官網核驗。", "專業身份不代表一定核准或取得最低利率。"],
    officialUrl: "https://www.o-bank.com/",
  },
  {
    id: "obank-online",
    bank: "王道銀行",
    mark: "王",
    product: "獨享貸",
    rate: "3.49% 起",
    rateValue: 3.49,
    fee: "NT$88 起",
    feeValue: 88,
    apr: "3.50% 起",
    aprValue: 3.5,
    monthly: "NT$4,299 起",
    maxAmount: "NT$88 萬",
    maxTerm: "最長 7 年",
    audience: "18–65 歲、有固定收入且自行完成線上申請者",
    tags: ["線上申辦", "小額"],
    status: "standard",
    analysis: ["限定自行完成線上申請與對保流程。", "開辦費與最高額度都採 88 的主題設計。", "一段式機動利率，最長 7 年。"],
    qualification: ["年齡參考區間為 18–65 歲。", "需有固定收入。", "申貸前與申貸中不能由專員協助補件或對保。"],
    cautions: ["接受專人協助可能不再符合此方案。", "18 個月限制清償期與違約金需先確認。"],
    officialUrl: "https://www.o-bank.com/",
  },
  {
    id: "sinopac-medical",
    bank: "永豐銀行",
    mark: "永",
    product: "醫護信貸",
    rate: "2.45% 起",
    rateValue: 2.45,
    fee: "NT$0 起",
    feeValue: 0,
    apr: "2.45% 起",
    aprValue: 2.45,
    monthly: "NT$4,149 起",
    maxAmount: "NT$800 萬",
    maxTerm: "依核定條件",
    audience: "醫療專業執照人士或地區醫院以上的正職員工",
    tags: ["專業人士", "醫護"],
    status: "standard",
    analysis: ["針對醫師與醫療機構正職人員設計。", "一段式機動利率，手續費依條件減免。", "最高額度參考為 800 萬元。"],
    qualification: ["具醫療相關高等考試或同等資格的專業執照人士。", "或任職於地區醫院以上的正職醫療機構員工。", "銀行可依個案要求其他文件。"],
    cautions: ["醫師與非醫師客群可能適用不同利率區間。", "提前清償與限制清償條件需看契約。"],
    officialUrl: "https://bank.sinopac.com/sinopacBT/webevents/psn_loan/index.html",
  },
  {
    id: "sinopac-public-service",
    bank: "永豐銀行",
    mark: "永",
    product: "軍公教貸",
    rate: "2.50% 起",
    rateValue: 2.5,
    fee: "NT$0 起",
    feeValue: 0,
    apr: "2.50% 起",
    aprValue: 2.5,
    monthly: "NT$4,157 起",
    maxAmount: "NT$500 萬",
    maxTerm: "最長 84 期",
    audience: "軍人、公務員、公營事業與公私立學校教職員工",
    tags: ["專業人士", "軍公教"],
    status: "standard",
    analysis: ["面向軍公教與公營事業從業人員。", "一段式機動利率，最高額度 500 萬元。", "24 小時線上申請，免保人與擔保品。"],
    qualification: ["適用公私立學校教職員工、公營事業員工與公務人員。", "警務、消防與軍人也可依條件評估。", "不符身份者可能轉為其他一般信貸方案。"],
    cautions: ["銀行仍保留補件與核貸權利。", "零手續費、最低利率與實際額度均取決於個案。"],
    officialUrl: "https://bank.sinopac.com/sinopacBT/webevents/psn_loan/index.html",
  },
];
