import type { Article, ArticleCategory, ArticleComplianceFlags, FileResource, LeadStatus, SiteSettings } from "./types";

export const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000";
export const allowPublicIndexing = process.env.BANKCLUB_ALLOW_INDEXING === "true";

export const settings: SiteSettings = {
  brandName: "銀行俱樂部",
  companyName: "國泰人壽保險股份有限公司",
  officeName: "永和通訊處",
  address: "东京都豐島区北大塚2-17-4 大塚Career大楼 B1",
  phone: "09-8584-7613",
  fax: "",
  mobile: "09-8584-7613",
  email: "xmu6611@gmail.com / g0985847613@gmail.com",
  fbGroupUrl: "https://www.facebook.com/share/g/1DzfRZ8fPw/?mibextid=wwXIfr",
  lineUrl: "https://line.me/R/ti/p/Gn148848",
  lineQrCodeUrl: "/brand/bank_club_line_qr.png",
  officialApplyUrl: "https://www.feib.com.tw/",
  gaMeasurementId: "",
  googleSearchConsoleVerification: "",
  launchReadiness: {
    domainHttpsConfirmed: false,
    lineEntryConfirmed: false,
    fbGroupConfirmed: false,
    officialApplyConfirmed: false,
    brandAuthorizationConfirmed: false,
    ga4Confirmed: false,
    searchConsoleConfirmed: false,
    notificationWebhookConfirmed: false,
    backupDrillConfirmed: false,
    pageSpeedConfirmed: false,
    legalReviewConfirmed: false,
    notes: "",
    updatedAt: "",
    updatedBy: "",
  },
};

export const statusLabels: Record<LeadStatus, string> = {
  new: "新線索",
  assigned: "已分配",
  contacted: "已聯繫",
  appointment_scheduled: "已預約",
  pre_reviewed: "已初審",
  pending_documents: "待補件",
  documents_received: "已補件",
  incomplete_documents: "資料不完整",
  proposal_suggested: "已建議方案",
  submitted_to_bank: "已送銀行",
  bank_reviewing: "銀行審核中",
  approved: "已核准",
  funded: "已撥款",
  rejected: "未核准",
  customer_gave_up: "客戶放棄",
  follow_up_later: "需再跟進",
  invalid: "無效線索",
  closed: "已結案",
};

export const loanLabels = {
  credit: "信用貸款",
  house: "房屋貸款",
  business: "企業貸款",
  unknown: "尚不確定",
};

export const identityLabels = {
  employee: "上班族",
  self_employed: "自營業主",
  business_owner: "企業主",
  home_owner: "有房族",
  other: "其他",
};

export const serviceCards = [
  {
    key: "credit",
    href: "/credit-loan",
    icon: "person",
    title: "信用貸款",
    subtitle: "彈性資金運用",
    railDescription: "滿足生活大小需求",
    body: "上班族、自營業主文件準備、網路申辦提醒與資金用途風險提示。",
    cta: "前往信貸頁",
  },
  {
    key: "house",
    href: "/house-loan",
    icon: "home",
    title: "房屋貸款",
    subtitle: "房屋購置與資金規劃",
    railDescription: "打造理想生活",
    body: "購屋、增貸、轉增貸、二胎房貸流程與試算工具。",
    cta: "前往房貸頁",
  },
  {
    key: "business",
    href: "/business-loan",
    icon: "building",
    title: "企業貸款",
    subtitle: "營運週轉與資金支持",
    railDescription: "助您企業成長",
    body: "企業主營運週轉、報稅與流水文件整理、審核重點提醒。",
    cta: "前往企業貸頁",
  },
];

export const processSteps = ["填寫需求", "專員初審", "準備文件", "銀行審核", "結果跟進"];

type SeedArticle = Omit<
  Article,
  | "coverImageUrl"
  | "coverImageAlt"
  | "fbPostStatus"
  | "fbPostUrl"
  | "fbPostedAt"
  | "fbPostNote"
  | "complianceFlags"
  | "complianceNotes"
  | "totalAnnualPercentageRate"
  | "annualPercentageRateDescription"
  | "feeDisclosureNote"
  | "complianceReviewedAt"
  | "complianceReviewedBy"
  | "publishedAt"
  | "publishedBy"
  | "lastModifiedBy"
  | "revisionHistory"
>;

export const seededArticleCategories: ArticleCategory[] = [
  {
    id: "category-credit",
    name: "信用貸款",
    slug: "credit-loan",
    description: "信用貸款申請資格、欄位填寫、駁件原因與公司優惠注意事項。",
    createdAt: "2026-06-30T00:00:00.000Z",
    updatedAt: "2026-06-30T00:00:00.000Z",
  },
  {
    id: "category-house",
    name: "房屋貸款",
    slug: "house-loan",
    description: "房屋增貸、轉增貸、二胎房貸與鑑價到撥款流程。",
    createdAt: "2026-06-30T00:00:00.000Z",
    updatedAt: "2026-06-30T00:00:00.000Z",
  },
  {
    id: "category-business",
    name: "企業貸款",
    slug: "business-loan",
    description: "企業營運週轉、報稅資料、銀行流水與審核重點。",
    createdAt: "2026-06-30T00:00:00.000Z",
    updatedAt: "2026-06-30T00:00:00.000Z",
  },
  {
    id: "category-docs",
    name: "文件準備",
    slug: "documents",
    description: "上班族、自營業主、有房族與企業主申請前文件清單。",
    createdAt: "2026-06-30T00:00:00.000Z",
    updatedAt: "2026-06-30T00:00:00.000Z",
  },
  {
    id: "category-flow",
    name: "申辦流程",
    slug: "application-flow",
    description: "網路申請、頁面當機、文件上傳與銀行審核等待流程。",
    createdAt: "2026-06-30T00:00:00.000Z",
    updatedAt: "2026-06-30T00:00:00.000Z",
  },
  {
    id: "category-risk",
    name: "風險提醒",
    slug: "risk",
    description: "資金用途、合規揭露、禁止用途與重要風險提醒。",
    createdAt: "2026-06-30T00:00:00.000Z",
    updatedAt: "2026-06-30T00:00:00.000Z",
  },
  {
    id: "category-community",
    name: "社群導流",
    slug: "community",
    description: "FB 社團、LINE 諮詢與站內內容互相導流。",
    createdAt: "2026-06-30T00:00:00.000Z",
    updatedAt: "2026-06-30T00:00:00.000Z",
  },
];

export const defaultAnnualPercentageRateDescription =
  "總費用年百分率不等於貸款利率，實際年百分率、利率、費用與核准結果以銀行最終審核及契約揭露為準。";

const articleCoverImages: Record<string, { url: string; alt: string }> = {
  "credit-application-fields": {
    url: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1200&q=80",
    alt: "桌面上的貸款申請文件與計算機",
  },
  "loan-purpose-risk": {
    url: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1200&q=80",
    alt: "金融文件旁的風險提醒筆記",
  },
  "loan-document-checklist": {
    url: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
    alt: "筆記型電腦與文件清單",
  },
  "online-application-back-button-crash": {
    url: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1200&q=80",
    alt: "線上申請流程中的電腦畫面",
  },
  "employee-self-employed-income-documents": {
    url: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=1200&q=80",
    alt: "專員整理財力證明資料",
  },
  "credit-loan-age-limit": {
    url: "https://images.unsplash.com/photo-1554224154-22dec7ec8818?auto=format&fit=crop&w=1200&q=80",
    alt: "信用貸款資格檢查文件",
  },
  "house-loan-refinance-second-mortgage": {
    url: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=1200&q=80",
    alt: "房屋貸款與住宅鑑價資料",
  },
  "business-loan-tax-documents": {
    url: "https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1200&q=80",
    alt: "企業主會議與營運貸款資料",
  },
  "credit-loan-rejection-reasons": {
    url: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=1200&q=80",
    alt: "信用貸款審核與文件檢查",
  },
  "bank-club-facebook-group-benefits": {
    url: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1200&q=80",
    alt: "社群討論與貸款資訊交流",
  },
};

function articleCover(article: SeedArticle) {
  return articleCoverImages[article.slug] || {
    url: "/brand/bank_club_hero.png",
    alt: `${article.title} 封面圖`,
  };
}

const seededArticleBases: SeedArticle[] = [
  {
    id: "article-credit-fields",
    title: "信貸網路申請欄位填寫教學",
    slug: "credit-application-fields",
    category: "信用貸款",
    excerpt: "申請金額、年限、案件來源與適用方案應依真實需求與專員確認結果填寫。",
    body: "網路申貸時，申請金額與年限不是網站承諾條件，而是銀行官方表單欄位。填寫前請先確認自身還款能力、資金用途與文件狀態。案件來源、方案類型等欄位如涉及公司優惠或綁約方案，應以專員確認與銀行頁面規則為準。申請過程中不要點上一頁；若頁面卡住、照片不清楚或資料上傳失敗，請立即聯繫專員協助。",
    seoTitle: "信貸網路申請欄位填寫教學｜銀行行員俱樂部",
    seoDescription: "整理信用貸款網路申請欄位、文件上傳、案件來源與方案類型注意事項。",
    keywords: ["信貸網路申請", "公司優惠信貸", "案件來源"],
    fbSummary: "網路申貸欄位不知道怎麼填？先看銀行行員俱樂部整理的注意事項，再依真實需求與專員確認結果申請。",
    ctaType: "form",
    status: "published",
    complianceChecked: true,
    createdAt: "2026-06-30T00:00:00.000Z",
    updatedAt: "2026-06-30T00:00:00.000Z",
  },
  {
    id: "article-purpose-risk",
    title: "信貸資金用途為什麼不能填投資理財",
    slug: "loan-purpose-risk",
    category: "風險提醒",
    excerpt: "貸款資金用途必須真實合法，不應填寫投資理財或股票操作等不符合銀行規範的用途。",
    body: "貸款申請的資金用途會影響銀行審核與風險判斷。網站不會教使用者包裝用途，也不建議填寫不真實內容。可依實際情況填寫生活消費、房屋修繕或合法營運週轉等用途；若不確定是否符合規範，應先諮詢專員或銀行。",
    seoTitle: "信貸資金用途規定｜不能填投資理財的原因｜銀行行員俱樂部",
    seoDescription: "說明信用貸款資金用途風險、合法用途與錯誤填寫可能造成的驳件風險。",
    keywords: ["貸款資金用途", "不能投資理財", "信貸風險"],
    fbSummary: "貸款資金用途要照真實用途填寫，別用不實說法包裝投資理財。",
    ctaType: "line",
    status: "published",
    complianceChecked: true,
    createdAt: "2026-06-30T00:00:00.000Z",
    updatedAt: "2026-06-30T00:00:00.000Z",
  },
  {
    id: "article-doc-checklist",
    title: "貸款申請前文件檢查清單",
    slug: "loan-document-checklist",
    category: "文件準備",
    excerpt: "上班族、自營業主、有房族與企業主常見文件一次整理。",
    body: "上班族常見文件包含身分證、薪轉、扣繳憑單與勞保資料。自營業主可先準備營業資料、銀行流水與報稅資料。有房族需留意權狀、收入證明與稅單。企業主則需準備營業登記、報稅資料、近六個月銀行存摺與負責人資料。高度敏感文件不建議直接上傳一般網站，應由專員確認後透過授權通道補件。",
    seoTitle: "貸款文件清單｜信貸、房貸、企業貸申請前準備｜銀行行員俱樂部",
    seoDescription: "比較上班族、自營業主、有房族與企業主申貸常見文件。",
    keywords: ["貸款文件清單", "財力證明", "信貸文件"],
    fbSummary: "申請前先把文件準備好，流程會順很多。這份清單適合先收藏。",
    ctaType: "fb",
    status: "published",
    complianceChecked: true,
    createdAt: "2026-06-30T00:00:00.000Z",
    updatedAt: "2026-06-30T00:00:00.000Z",
  },
  {
    id: "article-back-button-crash",
    title: "網路申貸千萬別點上一頁：頁面當機處理辦法",
    slug: "online-application-back-button-crash",
    category: "申辦流程",
    excerpt: "銀行官方申請頁可能因返回上一頁導致流程中斷，遇到卡住時先截圖再聯繫專員。",
    body: "網路申貸進入銀行官方頁面後，請依畫面順序填寫，不建議任意點上一頁或重複刷新。若頁面卡住、上傳失敗或欄位不確定，先截圖保留狀態，避免重複送件造成資料混亂，再透過 LINE 或電話聯繫專員協助確認下一步。",
    seoTitle: "網路申貸上一頁當機怎麼辦｜銀行行員俱樂部",
    seoDescription: "整理線上申貸頁面卡住、上一頁當機、文件上傳失敗時的處理方式。",
    keywords: ["網路申貸當機", "上一頁", "貸款申請流程"],
    fbSummary: "網路申貸卡住別急著重複送件，先截圖，再找專員確認流程。",
    ctaType: "line",
    status: "published",
    complianceChecked: true,
    createdAt: "2026-06-30T00:00:00.000Z",
    updatedAt: "2026-06-30T00:00:00.000Z",
  },
  {
    id: "article-employee-self-employed-docs",
    title: "上班族和自營業主財力證明準備清單",
    slug: "employee-self-employed-income-documents",
    category: "文件準備",
    excerpt: "薪轉、扣繳憑單、勞保資料、銀行流水與報稅資料各自適用不同身分。",
    body: "上班族通常可先準備薪轉紀錄、扣繳憑單、勞保資料與身分證。自營業主沒有固定薪資單時，可整理營業資料、銀行流水、報稅資料與其他可佐證收入的文件。文件是否足夠仍需依銀行規則與個案狀況確認，高度敏感資料請先與專員確認補件方式。",
    seoTitle: "上班族與自營業主財力證明準備｜銀行行員俱樂部",
    seoDescription: "比較上班族、自營業主申請信用貸款時常見財力證明與補件注意事項。",
    keywords: ["財力證明", "自營業主信貸", "上班族信貸"],
    fbSummary: "上班族和自營業主準備文件不一樣，先看清單再補件。",
    ctaType: "form",
    status: "published",
    complianceChecked: true,
    createdAt: "2026-06-30T00:00:00.000Z",
    updatedAt: "2026-06-30T00:00:00.000Z",
  },
  {
    id: "article-age-limit",
    title: "遠銀信用貸申請資格和年齡限制一次看懂",
    slug: "credit-loan-age-limit",
    category: "信用貸款",
    excerpt: "年齡、貸款年限、收入穩定度與信用紀錄都是信用貸款初步評估重點。",
    body: "信用貸款常見年齡區間為 18 至 65 歲，且年齡加貸款年限原則上不超過 65 歲。實際資格仍會依銀行、方案、收入穩定度、信用紀錄與負債狀況調整。網站僅提供申請前整理與諮詢，不代表銀行核准結果。",
    seoTitle: "信用貸款年齡限制與申請資格｜銀行行員俱樂部",
    seoDescription: "整理信用貸款常見年齡限制、收入、信用紀錄與申請前注意事項。",
    keywords: ["遠銀信用貸", "貸款年齡限制", "信用貸款資格"],
    fbSummary: "年齡加貸款年限會影響申請，送件前先檢查基本條件。",
    ctaType: "form",
    status: "published",
    complianceChecked: true,
    createdAt: "2026-06-30T00:00:00.000Z",
    updatedAt: "2026-06-30T00:00:00.000Z",
  },
  {
    id: "article-house-loan-types",
    title: "房屋增貸、轉增貸、二胎房貸差異比較",
    slug: "house-loan-refinance-second-mortgage",
    category: "房屋貸款",
    excerpt: "有房族可依房產條件、貸款餘額、資金需求與銀行鑑價結果比較方案。",
    body: "房屋增貸通常是原房貸以外再評估可貸空間；轉增貸則可能涉及轉換銀行與增加資金需求；二胎房貸是在既有一胎房貸之外另行評估。三者會受到房產鑑價、既有貸款餘額、收入與信用狀況影響，實際成數與利率以銀行審核為準。",
    seoTitle: "房屋增貸、轉增貸、二胎房貸差異｜銀行行員俱樂部",
    seoDescription: "比較房屋增貸、轉增貸與二胎房貸的用途、文件與審核重點。",
    keywords: ["房屋增貸", "轉增貸", "二胎房貸"],
    fbSummary: "有房族想動用資金，先分清楚增貸、轉增貸和二胎房貸。",
    ctaType: "form",
    status: "published",
    complianceChecked: true,
    createdAt: "2026-06-30T00:00:00.000Z",
    updatedAt: "2026-06-30T00:00:00.000Z",
  },
  {
    id: "article-business-tax-docs",
    title: "中小企業營運貸款需要哪些報稅資料",
    slug: "business-loan-tax-documents",
    category: "企業貸款",
    excerpt: "企業貸款通常需整理營業登記、報稅資料、銀行流水與負責人資料。",
    body: "中小企業申請營運週轉或企業信用貸時，可先準備營業登記、報稅資料、近六個月銀行存摺、公司財務資料與負責人身分資料。銀行會綜合評估營收穩定度、負債、信用與文件完整度，不同公司或商號條件可能需要不同補件。",
    seoTitle: "中小企業營運貸款報稅資料準備｜銀行行員俱樂部",
    seoDescription: "整理企業貸款、營運週轉金申請時常見報稅資料、銀行流水與負責人文件。",
    keywords: ["中小企業營運貸款", "企業周轉金", "報稅資料"],
    fbSummary: "企業貸款先把報稅資料、流水和負責人文件整理好，後續評估會更順。",
    ctaType: "form",
    status: "published",
    complianceChecked: true,
    createdAt: "2026-06-30T00:00:00.000Z",
    updatedAt: "2026-06-30T00:00:00.000Z",
  },
  {
    id: "article-rejection-reasons",
    title: "信用貸款常見駁件原因",
    slug: "credit-loan-rejection-reasons",
    category: "信用貸款",
    excerpt: "信用紀錄、收入穩定度、負債比、文件不完整與用途不符都可能影響審核。",
    body: "信用貸款是否通過由銀行審核決定。常見影響因素包含信用紀錄異常、收入不穩定、負債比偏高、文件不完整、用途不符合規範或資料前後不一致。若曾被駁件，建議先整理原因與文件缺口，再由專員協助判斷是否適合重新送件或改看其他方案。",
    seoTitle: "信用貸款常見駁件原因｜銀行行員俱樂部",
    seoDescription: "整理信用貸款被駁件的常見原因與申請前可檢查的方向。",
    keywords: ["信用貸款駁件", "貸款未核准", "信貸審核"],
    fbSummary: "信貸被駁件不一定只看收入，信用、負債、文件和用途都要一起檢查。",
    ctaType: "line",
    status: "published",
    complianceChecked: true,
    createdAt: "2026-06-30T00:00:00.000Z",
    updatedAt: "2026-06-30T00:00:00.000Z",
  },
  {
    id: "article-fb-group-benefits",
    title: "銀行行員俱樂部 FB 社團可以獲得哪些貸款資訊",
    slug: "bank-club-facebook-group-benefits",
    category: "社群導流",
    excerpt: "FB 社團提供最新貸款資訊、文件清單、流程教學與常見問題整理。",
    body: "銀行行員俱樂部 FB 社團會持續整理貸款申請教學、文件清單、常見問題與風險提醒。站內文章負責沉澱可搜尋內容，社團則適合接收最新貼文、互動問答與導流回網站。若需要一對一評估，仍建議透過 LINE 或表單留下需求。",
    seoTitle: "銀行行員俱樂部 FB 社團福利完整介紹｜銀行行員俱樂部",
    seoDescription: "介紹銀行行員俱樂部 FB 社團可取得的貸款資訊、文件清單、流程教學與 LINE 諮詢入口。",
    keywords: ["銀行行員俱樂部", "FB 社團", "貸款資訊"],
    fbSummary: "社團看最新貼文，網站看完整整理，需要一對一再進 LINE 或表單。",
    ctaType: "fb",
    status: "published",
    complianceChecked: true,
    createdAt: "2026-06-30T00:00:00.000Z",
    updatedAt: "2026-06-30T00:00:00.000Z",
  },
];

function detectComplianceFlags(article: SeedArticle): ArticleComplianceFlags {
  const text = `${article.title} ${article.excerpt} ${article.body} ${article.seoTitle} ${article.seoDescription}`;
  return {
    mentionsAmountOrTerm: /金額|年限|額度|700|10 年|十年/.test(text),
    mentionsRateOrFee: /利率|費用|總費用|年百分率|開辦費|帳戶管理費/.test(text),
    mentionsBinding: /綁約|公司優惠|優惠/.test(text),
    mentionsBankName: /銀行|遠銀|國泰/.test(text),
    containsGuaranteeLanguage: /保證|百分百|核准|過件|最低利率/.test(text),
    mentionsLoanPurpose: /用途|投資理財|股票|生活消費|營運週轉|房屋修繕/.test(text),
  };
}

export const seededArticles: Article[] = seededArticleBases.map((article) => ({
  ...article,
  coverImageUrl: articleCover(article).url,
  coverImageAlt: articleCover(article).alt,
  fbPostStatus: "not_started",
  fbPostUrl: "",
  fbPostedAt: "",
  fbPostNote: "",
  complianceFlags: detectComplianceFlags(article),
  complianceNotes: "首批種子文章已完成基本金融廣告與資金用途合規檢查。",
  totalAnnualPercentageRate: "",
  annualPercentageRateDescription: defaultAnnualPercentageRateDescription,
  feeDisclosureNote: "",
  complianceReviewedAt: article.updatedAt,
  complianceReviewedBy: "system",
  publishedAt: article.status === "published" ? article.createdAt : "",
  publishedBy: article.status === "published" ? "system" : "",
  lastModifiedBy: "system",
  revisionHistory: [
    {
      id: `${article.id}-seed-created`,
      actorId: "system",
      action: article.status === "published" ? "published" : "created",
      summary: "系統建立首批 SEO 文章並完成初始合規檢查。",
      createdAt: article.createdAt,
    },
  ],
}));

export const seededFiles: FileResource[] = [
  {
    id: "file-credit",
    title: "信用貸款文件清單",
    type: "credit_docs",
    visibility: "public",
    description: "身分證、薪轉、扣繳憑單、勞保與自營業主財力資料提醒。",
    content: "信用貸款文件清單\n1. 身分證正反面，拍攝需清晰對焦，僅在本站信貸專用申請模組上傳。\n2. 上班族：薪轉、扣繳憑單、勞保資料。\n3. 自營業主：營業資料、銀行流水、報稅資料。\n4. 財力資料請先透過 LINE 與專員確認補件方式，不在本站普通表單上傳。",
    sourceFilename: "",
    sourceFileMime: "",
    sourceFileSize: 0,
    sourceUploadedAt: "",
    version: 1,
    fileVersionHistory: [],
    downloads: 0,
    createdAt: "2026-06-30T00:00:00.000Z",
    updatedAt: "2026-06-30T00:00:00.000Z",
  },
  {
    id: "file-house",
    title: "房屋貸款文件清單",
    type: "house_docs",
    visibility: "public",
    description: "權狀、收入證明、稅單與銀行存摺等常見資料。",
    content: "房屋貸款文件清單\n1. 身分證。\n2. 房屋權狀。\n3. 收入證明、稅單、銀行存摺。\n4. 房產條件、貸款餘額與用途會影響評估。\n5. 權狀、收入、稅單與存摺等敏感文件請透過 LINE 或專員確認補件方式。",
    sourceFilename: "",
    sourceFileMime: "",
    sourceFileSize: 0,
    sourceUploadedAt: "",
    version: 1,
    fileVersionHistory: [],
    downloads: 0,
    createdAt: "2026-06-30T00:00:00.000Z",
    updatedAt: "2026-06-30T00:00:00.000Z",
  },
  {
    id: "file-business",
    title: "企業貸款文件清單",
    type: "business_docs",
    visibility: "public",
    description: "營業登記、報稅資料、銀行流水、負責人資料與公司財務資料提醒。",
    content: "企業貸款文件清單\n1. 營業登記或營業執照。\n2. 報稅資料與公司財務資料。\n3. 近 6 個月銀行存摺或主要往來帳戶流水。\n4. 負責人身分資料與財力證明。\n5. 依銀行要求補充營收、負債與用途說明。\n6. 報稅、存摺、執照與財力證明等敏感文件請透過 LINE 或專員確認補件方式。",
    sourceFilename: "",
    sourceFileMime: "",
    sourceFileSize: 0,
    sourceUploadedAt: "",
    version: 1,
    fileVersionHistory: [],
    downloads: 0,
    createdAt: "2026-06-30T00:00:00.000Z",
    updatedAt: "2026-06-30T00:00:00.000Z",
  },
  {
    id: "file-flow",
    title: "貸款申請流程圖文",
    type: "flow",
    visibility: "public",
    description: "從需求確認、文件準備、銀行送件到審核結果的流程提醒。",
    content: "貸款申請流程圖文\n1. 確認貸款類型、期望金額、還款能力與合法資金用途。\n2. 依身份別整理收入、財力與房屋或企業資料。\n3. 由專員協助確認銀行官方申請入口與補件方式。\n4. 送件後依銀行要求補充資料，避免重複送件或刷新官方頁面。\n5. 審核、核准、未核准或補件結果均以銀行最終通知為準。",
    sourceFilename: "",
    sourceFileMime: "",
    sourceFileSize: 0,
    sourceUploadedAt: "",
    version: 1,
    fileVersionHistory: [],
    downloads: 0,
    createdAt: "2026-06-30T00:00:00.000Z",
    updatedAt: "2026-06-30T00:00:00.000Z",
  },
  {
    id: "file-qa-card",
    title: "貸款常見 QA 圖卡文案",
    type: "qa_card",
    visibility: "public",
    description: "可用於網站、LINE 或 FB 社團的常見問題圖卡文字。",
    content: "貸款常見 QA 圖卡文案\nQ1：一定保證核貸嗎？\nA：不保證核貸、額度、利率或撥款結果，均以銀行最終審核為準。\n\nQ2：財力文件可以直接傳網站嗎？\nA：信貸身分證正反面只在本站專用申請模組上傳；財力、房產與企業敏感文件請透過 LINE 或專員確認補件方式。\n\nQ3：資金用途可以填投資理財等用途嗎？\nA：資金用途必須依本人真實需求、銀行官方頁面、最新規則與個案審核結果填寫，不得包裝或偽造用途。\n\nQ4：送出表單後會怎麼聯繫？\nA：專員會依使用者留下的手機或 LINE ID 進行跟進。",
    sourceFilename: "",
    sourceFileMime: "",
    sourceFileSize: 0,
    sourceUploadedAt: "",
    version: 1,
    fileVersionHistory: [],
    downloads: 0,
    createdAt: "2026-06-30T00:00:00.000Z",
    updatedAt: "2026-06-30T00:00:00.000Z",
  },
  {
    id: "file-fb-material",
    title: "FB 社團貼文素材包",
    type: "fb_material",
    visibility: "public",
    description: "社團貼文可複製的 CTA、風險提醒與站內導流文案。",
    content: "FB 社團貼文素材包\n貼文開頭：最近很多朋友詢問信貸、房貸與企業貸款文件要怎麼準備，先整理幾個送件前常見重點。\n\n重點提醒：\n1. 申請條件、額度、利率、年限與撥款結果都以銀行最終審核為準。\n2. 資金用途要真實合法，不包裝投資理財或股票操作用途。\n3. 敏感文件請透過銀行官方頁面或專員確認的授權通道補件。\n\nCTA：需要先確認文件和流程，可到銀行行員俱樂部填寫免費諮詢，或加入 LINE 一對一詢問。\n追蹤連結建議加上 utm_source=facebook&utm_medium=community&utm_campaign=fb-post。",
    sourceFilename: "",
    sourceFileMime: "",
    sourceFileSize: 0,
    sourceUploadedAt: "",
    version: 1,
    fileVersionHistory: [],
    downloads: 0,
    createdAt: "2026-06-30T00:00:00.000Z",
    updatedAt: "2026-06-30T00:00:00.000Z",
  },
];
