// Generated by scripts/build-land-tax-cpi-data.mjs from cpispl.xls.
// Source table: CPI; index base: 民國110年=100.
export const LAND_VALUE_TAX_CPI_METADATA = {
  "generatedAt": "2026-05-18T22:48:37.515Z",
  "sourceFile": "cpispl.xls",
  "sheetName": "CPI",
  "base": "民國110年=100",
  "count": 808,
  "firstPeriod": "048/01",
  "latestPeriod": "115/04"
};

export const LAND_VALUE_TAX_CPI_DATA = [
  {
    "period": "048/01",
    "year": 48,
    "month": 1,
    "index": 9.86
  },
  {
    "period": "048/02",
    "year": 48,
    "month": 2,
    "index": 9.94
  },
  {
    "period": "048/03",
    "year": 48,
    "month": 3,
    "index": 10.09
  },
  {
    "period": "048/04",
    "year": 48,
    "month": 4,
    "index": 10.08
  },
  {
    "period": "048/05",
    "year": 48,
    "month": 5,
    "index": 10.09
  },
  {
    "period": "048/06",
    "year": 48,
    "month": 6,
    "index": 10.26
  },
  {
    "period": "048/07",
    "year": 48,
    "month": 7,
    "index": 10.58
  },
  {
    "period": "048/08",
    "year": 48,
    "month": 8,
    "index": 11.16
  },
  {
    "period": "048/09",
    "year": 48,
    "month": 9,
    "index": 11.5
  },
  {
    "period": "048/10",
    "year": 48,
    "month": 10,
    "index": 11.32
  },
  {
    "period": "048/11",
    "year": 48,
    "month": 11,
    "index": 11
  },
  {
    "period": "048/12",
    "year": 48,
    "month": 12,
    "index": 10.99
  },
  {
    "period": "049/01",
    "year": 49,
    "month": 1,
    "index": 11.09
  },
  {
    "period": "049/02",
    "year": 49,
    "month": 2,
    "index": 11.34
  },
  {
    "period": "049/03",
    "year": 49,
    "month": 3,
    "index": 11.74
  },
  {
    "period": "049/04",
    "year": 49,
    "month": 4,
    "index": 12.3
  },
  {
    "period": "049/05",
    "year": 49,
    "month": 5,
    "index": 12.24
  },
  {
    "period": "049/06",
    "year": 49,
    "month": 6,
    "index": 12.6
  },
  {
    "period": "049/07",
    "year": 49,
    "month": 7,
    "index": 12.69
  },
  {
    "period": "049/08",
    "year": 49,
    "month": 8,
    "index": 13.25
  },
  {
    "period": "049/09",
    "year": 49,
    "month": 9,
    "index": 13.42
  },
  {
    "period": "049/10",
    "year": 49,
    "month": 10,
    "index": 13.3
  },
  {
    "period": "049/11",
    "year": 49,
    "month": 11,
    "index": 13.31
  },
  {
    "period": "049/12",
    "year": 49,
    "month": 12,
    "index": 13.07
  },
  {
    "period": "050/01",
    "year": 50,
    "month": 1,
    "index": 13.1
  },
  {
    "period": "050/02",
    "year": 50,
    "month": 2,
    "index": 13.35
  },
  {
    "period": "050/03",
    "year": 50,
    "month": 3,
    "index": 13.35
  },
  {
    "period": "050/04",
    "year": 50,
    "month": 4,
    "index": 13.45
  },
  {
    "period": "050/05",
    "year": 50,
    "month": 5,
    "index": 13.46
  },
  {
    "period": "050/06",
    "year": 50,
    "month": 6,
    "index": 13.46
  },
  {
    "period": "050/07",
    "year": 50,
    "month": 7,
    "index": 13.4
  },
  {
    "period": "050/08",
    "year": 50,
    "month": 8,
    "index": 13.56
  },
  {
    "period": "050/09",
    "year": 50,
    "month": 9,
    "index": 13.77
  },
  {
    "period": "050/10",
    "year": 50,
    "month": 10,
    "index": 13.86
  },
  {
    "period": "050/11",
    "year": 50,
    "month": 11,
    "index": 13.75
  },
  {
    "period": "050/12",
    "year": 50,
    "month": 12,
    "index": 13.62
  },
  {
    "period": "051/01",
    "year": 51,
    "month": 1,
    "index": 13.53
  },
  {
    "period": "051/02",
    "year": 51,
    "month": 2,
    "index": 13.68
  },
  {
    "period": "051/03",
    "year": 51,
    "month": 3,
    "index": 13.63
  },
  {
    "period": "051/04",
    "year": 51,
    "month": 4,
    "index": 13.69
  },
  {
    "period": "051/05",
    "year": 51,
    "month": 5,
    "index": 13.87
  },
  {
    "period": "051/06",
    "year": 51,
    "month": 6,
    "index": 13.79
  },
  {
    "period": "051/07",
    "year": 51,
    "month": 7,
    "index": 13.58
  },
  {
    "period": "051/08",
    "year": 51,
    "month": 8,
    "index": 13.72
  },
  {
    "period": "051/09",
    "year": 51,
    "month": 9,
    "index": 14.05
  },
  {
    "period": "051/10",
    "year": 51,
    "month": 10,
    "index": 14.31
  },
  {
    "period": "051/11",
    "year": 51,
    "month": 11,
    "index": 14.12
  },
  {
    "period": "051/12",
    "year": 51,
    "month": 12,
    "index": 14.01
  },
  {
    "period": "052/01",
    "year": 52,
    "month": 1,
    "index": 14.15
  },
  {
    "period": "052/02",
    "year": 52,
    "month": 2,
    "index": 14.16
  },
  {
    "period": "052/03",
    "year": 52,
    "month": 3,
    "index": 14.19
  },
  {
    "period": "052/04",
    "year": 52,
    "month": 4,
    "index": 14.28
  },
  {
    "period": "052/05",
    "year": 52,
    "month": 5,
    "index": 14.16
  },
  {
    "period": "052/06",
    "year": 52,
    "month": 6,
    "index": 14.03
  },
  {
    "period": "052/07",
    "year": 52,
    "month": 7,
    "index": 13.86
  },
  {
    "period": "052/08",
    "year": 52,
    "month": 8,
    "index": 13.89
  },
  {
    "period": "052/09",
    "year": 52,
    "month": 9,
    "index": 14.32
  },
  {
    "period": "052/10",
    "year": 52,
    "month": 10,
    "index": 14.31
  },
  {
    "period": "052/11",
    "year": 52,
    "month": 11,
    "index": 14.14
  },
  {
    "period": "052/12",
    "year": 52,
    "month": 12,
    "index": 14.1
  },
  {
    "period": "053/01",
    "year": 53,
    "month": 1,
    "index": 14.12
  },
  {
    "period": "053/02",
    "year": 53,
    "month": 2,
    "index": 14.14
  },
  {
    "period": "053/03",
    "year": 53,
    "month": 3,
    "index": 14.09
  },
  {
    "period": "053/04",
    "year": 53,
    "month": 4,
    "index": 14
  },
  {
    "period": "053/05",
    "year": 53,
    "month": 5,
    "index": 14.05
  },
  {
    "period": "053/06",
    "year": 53,
    "month": 6,
    "index": 13.94
  },
  {
    "period": "053/07",
    "year": 53,
    "month": 7,
    "index": 13.83
  },
  {
    "period": "053/08",
    "year": 53,
    "month": 8,
    "index": 13.99
  },
  {
    "period": "053/09",
    "year": 53,
    "month": 9,
    "index": 14.19
  },
  {
    "period": "053/10",
    "year": 53,
    "month": 10,
    "index": 14.4
  },
  {
    "period": "053/11",
    "year": 53,
    "month": 11,
    "index": 14.38
  },
  {
    "period": "053/12",
    "year": 53,
    "month": 12,
    "index": 14.19
  },
  {
    "period": "054/01",
    "year": 54,
    "month": 1,
    "index": 14
  },
  {
    "period": "054/02",
    "year": 54,
    "month": 2,
    "index": 13.96
  },
  {
    "period": "054/03",
    "year": 54,
    "month": 3,
    "index": 13.91
  },
  {
    "period": "054/04",
    "year": 54,
    "month": 4,
    "index": 13.96
  },
  {
    "period": "054/05",
    "year": 54,
    "month": 5,
    "index": 14.03
  },
  {
    "period": "054/06",
    "year": 54,
    "month": 6,
    "index": 14.1
  },
  {
    "period": "054/07",
    "year": 54,
    "month": 7,
    "index": 14.12
  },
  {
    "period": "054/08",
    "year": 54,
    "month": 8,
    "index": 14.2
  },
  {
    "period": "054/09",
    "year": 54,
    "month": 9,
    "index": 14.27
  },
  {
    "period": "054/10",
    "year": 54,
    "month": 10,
    "index": 14.16
  },
  {
    "period": "054/11",
    "year": 54,
    "month": 11,
    "index": 14.19
  },
  {
    "period": "054/12",
    "year": 54,
    "month": 12,
    "index": 14.27
  },
  {
    "period": "055/01",
    "year": 55,
    "month": 1,
    "index": 14.23
  },
  {
    "period": "055/02",
    "year": 55,
    "month": 2,
    "index": 14.03
  },
  {
    "period": "055/03",
    "year": 55,
    "month": 3,
    "index": 14.01
  },
  {
    "period": "055/04",
    "year": 55,
    "month": 4,
    "index": 14.11
  },
  {
    "period": "055/05",
    "year": 55,
    "month": 5,
    "index": 14.14
  },
  {
    "period": "055/06",
    "year": 55,
    "month": 6,
    "index": 14.47
  },
  {
    "period": "055/07",
    "year": 55,
    "month": 7,
    "index": 14.49
  },
  {
    "period": "055/08",
    "year": 55,
    "month": 8,
    "index": 14.42
  },
  {
    "period": "055/09",
    "year": 55,
    "month": 9,
    "index": 14.72
  },
  {
    "period": "055/10",
    "year": 55,
    "month": 10,
    "index": 14.82
  },
  {
    "period": "055/11",
    "year": 55,
    "month": 11,
    "index": 14.62
  },
  {
    "period": "055/12",
    "year": 55,
    "month": 12,
    "index": 14.51
  },
  {
    "period": "056/01",
    "year": 56,
    "month": 1,
    "index": 14.62
  },
  {
    "period": "056/02",
    "year": 56,
    "month": 2,
    "index": 14.9
  },
  {
    "period": "056/03",
    "year": 56,
    "month": 3,
    "index": 14.64
  },
  {
    "period": "056/04",
    "year": 56,
    "month": 4,
    "index": 14.61
  },
  {
    "period": "056/05",
    "year": 56,
    "month": 5,
    "index": 14.67
  },
  {
    "period": "056/06",
    "year": 56,
    "month": 6,
    "index": 14.78
  },
  {
    "period": "056/07",
    "year": 56,
    "month": 7,
    "index": 14.97
  },
  {
    "period": "056/08",
    "year": 56,
    "month": 8,
    "index": 14.94
  },
  {
    "period": "056/09",
    "year": 56,
    "month": 9,
    "index": 15.1
  },
  {
    "period": "056/10",
    "year": 56,
    "month": 10,
    "index": 15.02
  },
  {
    "period": "056/11",
    "year": 56,
    "month": 11,
    "index": 15
  },
  {
    "period": "056/12",
    "year": 56,
    "month": 12,
    "index": 15.15
  },
  {
    "period": "057/01",
    "year": 57,
    "month": 1,
    "index": 15.22
  },
  {
    "period": "057/02",
    "year": 57,
    "month": 2,
    "index": 15.11
  },
  {
    "period": "057/03",
    "year": 57,
    "month": 3,
    "index": 15.15
  },
  {
    "period": "057/04",
    "year": 57,
    "month": 4,
    "index": 15.8
  },
  {
    "period": "057/05",
    "year": 57,
    "month": 5,
    "index": 15.88
  },
  {
    "period": "057/06",
    "year": 57,
    "month": 6,
    "index": 16.17
  },
  {
    "period": "057/07",
    "year": 57,
    "month": 7,
    "index": 16.44
  },
  {
    "period": "057/08",
    "year": 57,
    "month": 8,
    "index": 16.86
  },
  {
    "period": "057/09",
    "year": 57,
    "month": 9,
    "index": 16.61
  },
  {
    "period": "057/10",
    "year": 57,
    "month": 10,
    "index": 16.72
  },
  {
    "period": "057/11",
    "year": 57,
    "month": 11,
    "index": 16.4
  },
  {
    "period": "057/12",
    "year": 57,
    "month": 12,
    "index": 16.07
  },
  {
    "period": "058/01",
    "year": 58,
    "month": 1,
    "index": 16.2
  },
  {
    "period": "058/02",
    "year": 58,
    "month": 2,
    "index": 16.41
  },
  {
    "period": "058/03",
    "year": 58,
    "month": 3,
    "index": 16.35
  },
  {
    "period": "058/04",
    "year": 58,
    "month": 4,
    "index": 16.43
  },
  {
    "period": "058/05",
    "year": 58,
    "month": 5,
    "index": 16.25
  },
  {
    "period": "058/06",
    "year": 58,
    "month": 6,
    "index": 16.39
  },
  {
    "period": "058/07",
    "year": 58,
    "month": 7,
    "index": 16.73
  },
  {
    "period": "058/08",
    "year": 58,
    "month": 8,
    "index": 17.06
  },
  {
    "period": "058/09",
    "year": 58,
    "month": 9,
    "index": 17.05
  },
  {
    "period": "058/10",
    "year": 58,
    "month": 10,
    "index": 18.6
  },
  {
    "period": "058/11",
    "year": 58,
    "month": 11,
    "index": 17.79
  },
  {
    "period": "058/12",
    "year": 58,
    "month": 12,
    "index": 17
  },
  {
    "period": "059/01",
    "year": 59,
    "month": 1,
    "index": 16.8
  },
  {
    "period": "059/02",
    "year": 59,
    "month": 2,
    "index": 17.08
  },
  {
    "period": "059/03",
    "year": 59,
    "month": 3,
    "index": 17.19
  },
  {
    "period": "059/04",
    "year": 59,
    "month": 4,
    "index": 17.27
  },
  {
    "period": "059/05",
    "year": 59,
    "month": 5,
    "index": 17.19
  },
  {
    "period": "059/06",
    "year": 59,
    "month": 6,
    "index": 17.05
  },
  {
    "period": "059/07",
    "year": 59,
    "month": 7,
    "index": 17.33
  },
  {
    "period": "059/08",
    "year": 59,
    "month": 8,
    "index": 17.84
  },
  {
    "period": "059/09",
    "year": 59,
    "month": 9,
    "index": 18.3
  },
  {
    "period": "059/10",
    "year": 59,
    "month": 10,
    "index": 18.02
  },
  {
    "period": "059/11",
    "year": 59,
    "month": 11,
    "index": 17.8
  },
  {
    "period": "059/12",
    "year": 59,
    "month": 12,
    "index": 17.63
  },
  {
    "period": "060/01",
    "year": 60,
    "month": 1,
    "index": 17.95
  },
  {
    "period": "060/02",
    "year": 60,
    "month": 2,
    "index": 17.88
  },
  {
    "period": "060/03",
    "year": 60,
    "month": 3,
    "index": 17.79
  },
  {
    "period": "060/04",
    "year": 60,
    "month": 4,
    "index": 17.75
  },
  {
    "period": "060/05",
    "year": 60,
    "month": 5,
    "index": 17.77
  },
  {
    "period": "060/06",
    "year": 60,
    "month": 6,
    "index": 17.77
  },
  {
    "period": "060/07",
    "year": 60,
    "month": 7,
    "index": 17.78
  },
  {
    "period": "060/08",
    "year": 60,
    "month": 8,
    "index": 18.09
  },
  {
    "period": "060/09",
    "year": 60,
    "month": 9,
    "index": 18.08
  },
  {
    "period": "060/10",
    "year": 60,
    "month": 10,
    "index": 18.2
  },
  {
    "period": "060/11",
    "year": 60,
    "month": 11,
    "index": 18.15
  },
  {
    "period": "060/12",
    "year": 60,
    "month": 12,
    "index": 18.11
  },
  {
    "period": "061/01",
    "year": 61,
    "month": 1,
    "index": 17.84
  },
  {
    "period": "061/02",
    "year": 61,
    "month": 2,
    "index": 18.22
  },
  {
    "period": "061/03",
    "year": 61,
    "month": 3,
    "index": 18.18
  },
  {
    "period": "061/04",
    "year": 61,
    "month": 4,
    "index": 18.2
  },
  {
    "period": "061/05",
    "year": 61,
    "month": 5,
    "index": 18.29
  },
  {
    "period": "061/06",
    "year": 61,
    "month": 6,
    "index": 18.48
  },
  {
    "period": "061/07",
    "year": 61,
    "month": 7,
    "index": 18.64
  },
  {
    "period": "061/08",
    "year": 61,
    "month": 8,
    "index": 19.3
  },
  {
    "period": "061/09",
    "year": 61,
    "month": 9,
    "index": 19.25
  },
  {
    "period": "061/10",
    "year": 61,
    "month": 10,
    "index": 18.5
  },
  {
    "period": "061/11",
    "year": 61,
    "month": 11,
    "index": 18.26
  },
  {
    "period": "061/12",
    "year": 61,
    "month": 12,
    "index": 18.58
  },
  {
    "period": "062/01",
    "year": 62,
    "month": 1,
    "index": 18.1
  },
  {
    "period": "062/02",
    "year": 62,
    "month": 2,
    "index": 18.36
  },
  {
    "period": "062/03",
    "year": 62,
    "month": 3,
    "index": 18.3
  },
  {
    "period": "062/04",
    "year": 62,
    "month": 4,
    "index": 18.57
  },
  {
    "period": "062/05",
    "year": 62,
    "month": 5,
    "index": 18.81
  },
  {
    "period": "062/06",
    "year": 62,
    "month": 6,
    "index": 19.01
  },
  {
    "period": "062/07",
    "year": 62,
    "month": 7,
    "index": 19.55
  },
  {
    "period": "062/08",
    "year": 62,
    "month": 8,
    "index": 19.98
  },
  {
    "period": "062/09",
    "year": 62,
    "month": 9,
    "index": 20.82
  },
  {
    "period": "062/10",
    "year": 62,
    "month": 10,
    "index": 22.46
  },
  {
    "period": "062/11",
    "year": 62,
    "month": 11,
    "index": 22.91
  },
  {
    "period": "062/12",
    "year": 62,
    "month": 12,
    "index": 23.04
  },
  {
    "period": "063/01",
    "year": 63,
    "month": 1,
    "index": 25.3
  },
  {
    "period": "063/02",
    "year": 63,
    "month": 2,
    "index": 29.14
  },
  {
    "period": "063/03",
    "year": 63,
    "month": 3,
    "index": 29.54
  },
  {
    "period": "063/04",
    "year": 63,
    "month": 4,
    "index": 29.34
  },
  {
    "period": "063/05",
    "year": 63,
    "month": 5,
    "index": 29.1
  },
  {
    "period": "063/06",
    "year": 63,
    "month": 6,
    "index": 29.01
  },
  {
    "period": "063/07",
    "year": 63,
    "month": 7,
    "index": 29.39
  },
  {
    "period": "063/08",
    "year": 63,
    "month": 8,
    "index": 29.72
  },
  {
    "period": "063/09",
    "year": 63,
    "month": 9,
    "index": 30.67
  },
  {
    "period": "063/10",
    "year": 63,
    "month": 10,
    "index": 30.62
  },
  {
    "period": "063/11",
    "year": 63,
    "month": 11,
    "index": 31.06
  },
  {
    "period": "063/12",
    "year": 63,
    "month": 12,
    "index": 30.88
  },
  {
    "period": "064/01",
    "year": 64,
    "month": 1,
    "index": 30.59
  },
  {
    "period": "064/02",
    "year": 64,
    "month": 2,
    "index": 30.63
  },
  {
    "period": "064/03",
    "year": 64,
    "month": 3,
    "index": 30.37
  },
  {
    "period": "064/04",
    "year": 64,
    "month": 4,
    "index": 30.57
  },
  {
    "period": "064/05",
    "year": 64,
    "month": 5,
    "index": 30.59
  },
  {
    "period": "064/06",
    "year": 64,
    "month": 6,
    "index": 31.28
  },
  {
    "period": "064/07",
    "year": 64,
    "month": 7,
    "index": 31.28
  },
  {
    "period": "064/08",
    "year": 64,
    "month": 8,
    "index": 31.39
  },
  {
    "period": "064/09",
    "year": 64,
    "month": 9,
    "index": 31.35
  },
  {
    "period": "064/10",
    "year": 64,
    "month": 10,
    "index": 31.76
  },
  {
    "period": "064/11",
    "year": 64,
    "month": 11,
    "index": 31.5
  },
  {
    "period": "064/12",
    "year": 64,
    "month": 12,
    "index": 30.94
  },
  {
    "period": "065/01",
    "year": 65,
    "month": 1,
    "index": 31.48
  },
  {
    "period": "065/02",
    "year": 65,
    "month": 2,
    "index": 31.59
  },
  {
    "period": "065/03",
    "year": 65,
    "month": 3,
    "index": 31.84
  },
  {
    "period": "065/04",
    "year": 65,
    "month": 4,
    "index": 31.92
  },
  {
    "period": "065/05",
    "year": 65,
    "month": 5,
    "index": 31.76
  },
  {
    "period": "065/06",
    "year": 65,
    "month": 6,
    "index": 31.63
  },
  {
    "period": "065/07",
    "year": 65,
    "month": 7,
    "index": 31.77
  },
  {
    "period": "065/08",
    "year": 65,
    "month": 8,
    "index": 32
  },
  {
    "period": "065/09",
    "year": 65,
    "month": 9,
    "index": 31.97
  },
  {
    "period": "065/10",
    "year": 65,
    "month": 10,
    "index": 31.8
  },
  {
    "period": "065/11",
    "year": 65,
    "month": 11,
    "index": 31.72
  },
  {
    "period": "065/12",
    "year": 65,
    "month": 12,
    "index": 32.06
  },
  {
    "period": "066/01",
    "year": 66,
    "month": 1,
    "index": 32.49
  },
  {
    "period": "066/02",
    "year": 66,
    "month": 2,
    "index": 33.01
  },
  {
    "period": "066/03",
    "year": 66,
    "month": 3,
    "index": 32.89
  },
  {
    "period": "066/04",
    "year": 66,
    "month": 4,
    "index": 33.14
  },
  {
    "period": "066/05",
    "year": 66,
    "month": 5,
    "index": 33.28
  },
  {
    "period": "066/06",
    "year": 66,
    "month": 6,
    "index": 34.33
  },
  {
    "period": "066/07",
    "year": 66,
    "month": 7,
    "index": 34.36
  },
  {
    "period": "066/08",
    "year": 66,
    "month": 8,
    "index": 35.88
  },
  {
    "period": "066/09",
    "year": 66,
    "month": 9,
    "index": 35.38
  },
  {
    "period": "066/10",
    "year": 66,
    "month": 10,
    "index": 35
  },
  {
    "period": "066/11",
    "year": 66,
    "month": 11,
    "index": 34.4
  },
  {
    "period": "066/12",
    "year": 66,
    "month": 12,
    "index": 34.23
  },
  {
    "period": "067/01",
    "year": 67,
    "month": 1,
    "index": 34.82
  },
  {
    "period": "067/02",
    "year": 67,
    "month": 2,
    "index": 35.08
  },
  {
    "period": "067/03",
    "year": 67,
    "month": 3,
    "index": 35.12
  },
  {
    "period": "067/04",
    "year": 67,
    "month": 4,
    "index": 35.77
  },
  {
    "period": "067/05",
    "year": 67,
    "month": 5,
    "index": 35.75
  },
  {
    "period": "067/06",
    "year": 67,
    "month": 6,
    "index": 35.72
  },
  {
    "period": "067/07",
    "year": 67,
    "month": 7,
    "index": 35.62
  },
  {
    "period": "067/08",
    "year": 67,
    "month": 8,
    "index": 36.27
  },
  {
    "period": "067/09",
    "year": 67,
    "month": 9,
    "index": 36.83
  },
  {
    "period": "067/10",
    "year": 67,
    "month": 10,
    "index": 37.13
  },
  {
    "period": "067/11",
    "year": 67,
    "month": 11,
    "index": 37.01
  },
  {
    "period": "067/12",
    "year": 67,
    "month": 12,
    "index": 36.85
  },
  {
    "period": "068/01",
    "year": 68,
    "month": 1,
    "index": 36.97
  },
  {
    "period": "068/02",
    "year": 68,
    "month": 2,
    "index": 37.14
  },
  {
    "period": "068/03",
    "year": 68,
    "month": 3,
    "index": 37.65
  },
  {
    "period": "068/04",
    "year": 68,
    "month": 4,
    "index": 38.4
  },
  {
    "period": "068/05",
    "year": 68,
    "month": 5,
    "index": 38.73
  },
  {
    "period": "068/06",
    "year": 68,
    "month": 6,
    "index": 39.13
  },
  {
    "period": "068/07",
    "year": 68,
    "month": 7,
    "index": 39.48
  },
  {
    "period": "068/08",
    "year": 68,
    "month": 8,
    "index": 40.5
  },
  {
    "period": "068/09",
    "year": 68,
    "month": 9,
    "index": 41.82
  },
  {
    "period": "068/10",
    "year": 68,
    "month": 10,
    "index": 41.71
  },
  {
    "period": "068/11",
    "year": 68,
    "month": 11,
    "index": 41.11
  },
  {
    "period": "068/12",
    "year": 68,
    "month": 12,
    "index": 41.46
  },
  {
    "period": "069/01",
    "year": 69,
    "month": 1,
    "index": 43.15
  },
  {
    "period": "069/02",
    "year": 69,
    "month": 2,
    "index": 44.01
  },
  {
    "period": "069/03",
    "year": 69,
    "month": 3,
    "index": 44.25
  },
  {
    "period": "069/04",
    "year": 69,
    "month": 4,
    "index": 44.47
  },
  {
    "period": "069/05",
    "year": 69,
    "month": 5,
    "index": 45.31
  },
  {
    "period": "069/06",
    "year": 69,
    "month": 6,
    "index": 46.52
  },
  {
    "period": "069/07",
    "year": 69,
    "month": 7,
    "index": 46.85
  },
  {
    "period": "069/08",
    "year": 69,
    "month": 8,
    "index": 47.92
  },
  {
    "period": "069/09",
    "year": 69,
    "month": 9,
    "index": 49.77
  },
  {
    "period": "069/10",
    "year": 69,
    "month": 10,
    "index": 50.65
  },
  {
    "period": "069/11",
    "year": 69,
    "month": 11,
    "index": 50.72
  },
  {
    "period": "069/12",
    "year": 69,
    "month": 12,
    "index": 50.66
  },
  {
    "period": "070/01",
    "year": 70,
    "month": 1,
    "index": 52.95
  },
  {
    "period": "070/02",
    "year": 70,
    "month": 2,
    "index": 53.85
  },
  {
    "period": "070/03",
    "year": 70,
    "month": 3,
    "index": 54.09
  },
  {
    "period": "070/04",
    "year": 70,
    "month": 4,
    "index": 54.3
  },
  {
    "period": "070/05",
    "year": 70,
    "month": 5,
    "index": 54.09
  },
  {
    "period": "070/06",
    "year": 70,
    "month": 6,
    "index": 54.61
  },
  {
    "period": "070/07",
    "year": 70,
    "month": 7,
    "index": 54.82
  },
  {
    "period": "070/08",
    "year": 70,
    "month": 8,
    "index": 55.36
  },
  {
    "period": "070/09",
    "year": 70,
    "month": 9,
    "index": 56.02
  },
  {
    "period": "070/10",
    "year": 70,
    "month": 10,
    "index": 55.71
  },
  {
    "period": "070/11",
    "year": 70,
    "month": 11,
    "index": 55.34
  },
  {
    "period": "070/12",
    "year": 70,
    "month": 12,
    "index": 55.26
  },
  {
    "period": "071/01",
    "year": 71,
    "month": 1,
    "index": 55.62
  },
  {
    "period": "071/02",
    "year": 71,
    "month": 2,
    "index": 55.44
  },
  {
    "period": "071/03",
    "year": 71,
    "month": 3,
    "index": 55.59
  },
  {
    "period": "071/04",
    "year": 71,
    "month": 4,
    "index": 55.73
  },
  {
    "period": "071/05",
    "year": 71,
    "month": 5,
    "index": 56.07
  },
  {
    "period": "071/06",
    "year": 71,
    "month": 6,
    "index": 56.18
  },
  {
    "period": "071/07",
    "year": 71,
    "month": 7,
    "index": 56.15
  },
  {
    "period": "071/08",
    "year": 71,
    "month": 8,
    "index": 57.85
  },
  {
    "period": "071/09",
    "year": 71,
    "month": 9,
    "index": 57.31
  },
  {
    "period": "071/10",
    "year": 71,
    "month": 10,
    "index": 56.85
  },
  {
    "period": "071/11",
    "year": 71,
    "month": 11,
    "index": 56.39
  },
  {
    "period": "071/12",
    "year": 71,
    "month": 12,
    "index": 56.6
  },
  {
    "period": "072/01",
    "year": 72,
    "month": 1,
    "index": 56.62
  },
  {
    "period": "072/02",
    "year": 72,
    "month": 2,
    "index": 57.19
  },
  {
    "period": "072/03",
    "year": 72,
    "month": 3,
    "index": 57.43
  },
  {
    "period": "072/04",
    "year": 72,
    "month": 4,
    "index": 57.68
  },
  {
    "period": "072/05",
    "year": 72,
    "month": 5,
    "index": 57.28
  },
  {
    "period": "072/06",
    "year": 72,
    "month": 6,
    "index": 57.71
  },
  {
    "period": "072/07",
    "year": 72,
    "month": 7,
    "index": 57.06
  },
  {
    "period": "072/08",
    "year": 72,
    "month": 8,
    "index": 57.03
  },
  {
    "period": "072/09",
    "year": 72,
    "month": 9,
    "index": 57.21
  },
  {
    "period": "072/10",
    "year": 72,
    "month": 10,
    "index": 57.19
  },
  {
    "period": "072/11",
    "year": 72,
    "month": 11,
    "index": 56.71
  },
  {
    "period": "072/12",
    "year": 72,
    "month": 12,
    "index": 55.93
  },
  {
    "period": "073/01",
    "year": 73,
    "month": 1,
    "index": 55.97
  },
  {
    "period": "073/02",
    "year": 73,
    "month": 2,
    "index": 56.54
  },
  {
    "period": "073/03",
    "year": 73,
    "month": 3,
    "index": 56.69
  },
  {
    "period": "073/04",
    "year": 73,
    "month": 4,
    "index": 56.8
  },
  {
    "period": "073/05",
    "year": 73,
    "month": 5,
    "index": 57.49
  },
  {
    "period": "073/06",
    "year": 73,
    "month": 6,
    "index": 57.44
  },
  {
    "period": "073/07",
    "year": 73,
    "month": 7,
    "index": 57.28
  },
  {
    "period": "073/08",
    "year": 73,
    "month": 8,
    "index": 57.49
  },
  {
    "period": "073/09",
    "year": 73,
    "month": 9,
    "index": 57.69
  },
  {
    "period": "073/10",
    "year": 73,
    "month": 10,
    "index": 57.46
  },
  {
    "period": "073/11",
    "year": 73,
    "month": 11,
    "index": 57.13
  },
  {
    "period": "073/12",
    "year": 73,
    "month": 12,
    "index": 56.85
  },
  {
    "period": "074/01",
    "year": 74,
    "month": 1,
    "index": 56.88
  },
  {
    "period": "074/02",
    "year": 74,
    "month": 2,
    "index": 57.33
  },
  {
    "period": "074/03",
    "year": 74,
    "month": 3,
    "index": 57.36
  },
  {
    "period": "074/04",
    "year": 74,
    "month": 4,
    "index": 57.08
  },
  {
    "period": "074/05",
    "year": 74,
    "month": 5,
    "index": 56.9
  },
  {
    "period": "074/06",
    "year": 74,
    "month": 6,
    "index": 56.81
  },
  {
    "period": "074/07",
    "year": 74,
    "month": 7,
    "index": 56.87
  },
  {
    "period": "074/08",
    "year": 74,
    "month": 8,
    "index": 56.62
  },
  {
    "period": "074/09",
    "year": 74,
    "month": 9,
    "index": 57.56
  },
  {
    "period": "074/10",
    "year": 74,
    "month": 10,
    "index": 57.5
  },
  {
    "period": "074/11",
    "year": 74,
    "month": 11,
    "index": 56.7
  },
  {
    "period": "074/12",
    "year": 74,
    "month": 12,
    "index": 56.11
  },
  {
    "period": "075/01",
    "year": 75,
    "month": 1,
    "index": 56.64
  },
  {
    "period": "075/02",
    "year": 75,
    "month": 2,
    "index": 56.8
  },
  {
    "period": "075/03",
    "year": 75,
    "month": 3,
    "index": 56.79
  },
  {
    "period": "075/04",
    "year": 75,
    "month": 4,
    "index": 56.93
  },
  {
    "period": "075/05",
    "year": 75,
    "month": 5,
    "index": 57.01
  },
  {
    "period": "075/06",
    "year": 75,
    "month": 6,
    "index": 57.15
  },
  {
    "period": "075/07",
    "year": 75,
    "month": 7,
    "index": 57.01
  },
  {
    "period": "075/08",
    "year": 75,
    "month": 8,
    "index": 57.32
  },
  {
    "period": "075/09",
    "year": 75,
    "month": 9,
    "index": 58.78
  },
  {
    "period": "075/10",
    "year": 75,
    "month": 10,
    "index": 58.65
  },
  {
    "period": "075/11",
    "year": 75,
    "month": 11,
    "index": 57.84
  },
  {
    "period": "075/12",
    "year": 75,
    "month": 12,
    "index": 57.58
  },
  {
    "period": "076/01",
    "year": 76,
    "month": 1,
    "index": 57.43
  },
  {
    "period": "076/02",
    "year": 76,
    "month": 2,
    "index": 57.31
  },
  {
    "period": "076/03",
    "year": 76,
    "month": 3,
    "index": 56.86
  },
  {
    "period": "076/04",
    "year": 76,
    "month": 4,
    "index": 57.06
  },
  {
    "period": "076/05",
    "year": 76,
    "month": 5,
    "index": 57.07
  },
  {
    "period": "076/06",
    "year": 76,
    "month": 6,
    "index": 57.11
  },
  {
    "period": "076/07",
    "year": 76,
    "month": 7,
    "index": 57.77
  },
  {
    "period": "076/08",
    "year": 76,
    "month": 8,
    "index": 58.24
  },
  {
    "period": "076/09",
    "year": 76,
    "month": 9,
    "index": 58.45
  },
  {
    "period": "076/10",
    "year": 76,
    "month": 10,
    "index": 57.93
  },
  {
    "period": "076/11",
    "year": 76,
    "month": 11,
    "index": 58.09
  },
  {
    "period": "076/12",
    "year": 76,
    "month": 12,
    "index": 58.69
  },
  {
    "period": "077/01",
    "year": 77,
    "month": 1,
    "index": 57.74
  },
  {
    "period": "077/02",
    "year": 77,
    "month": 2,
    "index": 57.51
  },
  {
    "period": "077/03",
    "year": 77,
    "month": 3,
    "index": 57.19
  },
  {
    "period": "077/04",
    "year": 77,
    "month": 4,
    "index": 57.26
  },
  {
    "period": "077/05",
    "year": 77,
    "month": 5,
    "index": 57.91
  },
  {
    "period": "077/06",
    "year": 77,
    "month": 6,
    "index": 58.26
  },
  {
    "period": "077/07",
    "year": 77,
    "month": 7,
    "index": 58.26
  },
  {
    "period": "077/08",
    "year": 77,
    "month": 8,
    "index": 59.09
  },
  {
    "period": "077/09",
    "year": 77,
    "month": 9,
    "index": 59.28
  },
  {
    "period": "077/10",
    "year": 77,
    "month": 10,
    "index": 59.7
  },
  {
    "period": "077/11",
    "year": 77,
    "month": 11,
    "index": 59.39
  },
  {
    "period": "077/12",
    "year": 77,
    "month": 12,
    "index": 59.34
  },
  {
    "period": "078/01",
    "year": 78,
    "month": 1,
    "index": 59.34
  },
  {
    "period": "078/02",
    "year": 78,
    "month": 2,
    "index": 59.86
  },
  {
    "period": "078/03",
    "year": 78,
    "month": 3,
    "index": 60.01
  },
  {
    "period": "078/04",
    "year": 78,
    "month": 4,
    "index": 60.54
  },
  {
    "period": "078/05",
    "year": 78,
    "month": 5,
    "index": 60.99
  },
  {
    "period": "078/06",
    "year": 78,
    "month": 6,
    "index": 60.83
  },
  {
    "period": "078/07",
    "year": 78,
    "month": 7,
    "index": 60.54
  },
  {
    "period": "078/08",
    "year": 78,
    "month": 8,
    "index": 61.05
  },
  {
    "period": "078/09",
    "year": 78,
    "month": 9,
    "index": 62.65
  },
  {
    "period": "078/10",
    "year": 78,
    "month": 10,
    "index": 63.25
  },
  {
    "period": "078/11",
    "year": 78,
    "month": 11,
    "index": 61.62
  },
  {
    "period": "078/12",
    "year": 78,
    "month": 12,
    "index": 61.2
  },
  {
    "period": "079/01",
    "year": 79,
    "month": 1,
    "index": 61.63
  },
  {
    "period": "079/02",
    "year": 79,
    "month": 2,
    "index": 61.54
  },
  {
    "period": "079/03",
    "year": 79,
    "month": 3,
    "index": 62
  },
  {
    "period": "079/04",
    "year": 79,
    "month": 4,
    "index": 62.61
  },
  {
    "period": "079/05",
    "year": 79,
    "month": 5,
    "index": 63.27
  },
  {
    "period": "079/06",
    "year": 79,
    "month": 6,
    "index": 63.03
  },
  {
    "period": "079/07",
    "year": 79,
    "month": 7,
    "index": 63.45
  },
  {
    "period": "079/08",
    "year": 79,
    "month": 8,
    "index": 64.5
  },
  {
    "period": "079/09",
    "year": 79,
    "month": 9,
    "index": 66.74
  },
  {
    "period": "079/10",
    "year": 79,
    "month": 10,
    "index": 65.3
  },
  {
    "period": "079/11",
    "year": 79,
    "month": 11,
    "index": 64.04
  },
  {
    "period": "079/12",
    "year": 79,
    "month": 12,
    "index": 63.99
  },
  {
    "period": "080/01",
    "year": 80,
    "month": 1,
    "index": 64.7
  },
  {
    "period": "080/02",
    "year": 80,
    "month": 2,
    "index": 65.09
  },
  {
    "period": "080/03",
    "year": 80,
    "month": 3,
    "index": 64.77
  },
  {
    "period": "080/04",
    "year": 80,
    "month": 4,
    "index": 65.19
  },
  {
    "period": "080/05",
    "year": 80,
    "month": 5,
    "index": 65.41
  },
  {
    "period": "080/06",
    "year": 80,
    "month": 6,
    "index": 65.57
  },
  {
    "period": "080/07",
    "year": 80,
    "month": 7,
    "index": 66.02
  },
  {
    "period": "080/08",
    "year": 80,
    "month": 8,
    "index": 66.17
  },
  {
    "period": "080/09",
    "year": 80,
    "month": 9,
    "index": 66.27
  },
  {
    "period": "080/10",
    "year": 80,
    "month": 10,
    "index": 66.92
  },
  {
    "period": "080/11",
    "year": 80,
    "month": 11,
    "index": 67.12
  },
  {
    "period": "080/12",
    "year": 80,
    "month": 12,
    "index": 66.48
  },
  {
    "period": "081/01",
    "year": 81,
    "month": 1,
    "index": 67.14
  },
  {
    "period": "081/02",
    "year": 81,
    "month": 2,
    "index": 67.73
  },
  {
    "period": "081/03",
    "year": 81,
    "month": 3,
    "index": 67.82
  },
  {
    "period": "081/04",
    "year": 81,
    "month": 4,
    "index": 68.92
  },
  {
    "period": "081/05",
    "year": 81,
    "month": 5,
    "index": 69.15
  },
  {
    "period": "081/06",
    "year": 81,
    "month": 6,
    "index": 68.96
  },
  {
    "period": "081/07",
    "year": 81,
    "month": 7,
    "index": 68.46
  },
  {
    "period": "081/08",
    "year": 81,
    "month": 8,
    "index": 68.15
  },
  {
    "period": "081/09",
    "year": 81,
    "month": 9,
    "index": 70.35
  },
  {
    "period": "081/10",
    "year": 81,
    "month": 10,
    "index": 70.32
  },
  {
    "period": "081/11",
    "year": 81,
    "month": 11,
    "index": 69.2
  },
  {
    "period": "081/12",
    "year": 81,
    "month": 12,
    "index": 68.75
  },
  {
    "period": "082/01",
    "year": 82,
    "month": 1,
    "index": 69.59
  },
  {
    "period": "082/02",
    "year": 82,
    "month": 2,
    "index": 69.8
  },
  {
    "period": "082/03",
    "year": 82,
    "month": 3,
    "index": 70.02
  },
  {
    "period": "082/04",
    "year": 82,
    "month": 4,
    "index": 70.83
  },
  {
    "period": "082/05",
    "year": 82,
    "month": 5,
    "index": 70.59
  },
  {
    "period": "082/06",
    "year": 82,
    "month": 6,
    "index": 71.96
  },
  {
    "period": "082/07",
    "year": 82,
    "month": 7,
    "index": 70.71
  },
  {
    "period": "082/08",
    "year": 82,
    "month": 8,
    "index": 70.42
  },
  {
    "period": "082/09",
    "year": 82,
    "month": 9,
    "index": 70.87
  },
  {
    "period": "082/10",
    "year": 82,
    "month": 10,
    "index": 71.18
  },
  {
    "period": "082/11",
    "year": 82,
    "month": 11,
    "index": 71.34
  },
  {
    "period": "082/12",
    "year": 82,
    "month": 12,
    "index": 71.93
  },
  {
    "period": "083/01",
    "year": 83,
    "month": 1,
    "index": 71.61
  },
  {
    "period": "083/02",
    "year": 83,
    "month": 2,
    "index": 72.54
  },
  {
    "period": "083/03",
    "year": 83,
    "month": 3,
    "index": 72.34
  },
  {
    "period": "083/04",
    "year": 83,
    "month": 4,
    "index": 73
  },
  {
    "period": "083/05",
    "year": 83,
    "month": 5,
    "index": 73.68
  },
  {
    "period": "083/06",
    "year": 83,
    "month": 6,
    "index": 73.49
  },
  {
    "period": "083/07",
    "year": 83,
    "month": 7,
    "index": 73.65
  },
  {
    "period": "083/08",
    "year": 83,
    "month": 8,
    "index": 75.38
  },
  {
    "period": "083/09",
    "year": 83,
    "month": 9,
    "index": 75.61
  },
  {
    "period": "083/10",
    "year": 83,
    "month": 10,
    "index": 74.79
  },
  {
    "period": "083/11",
    "year": 83,
    "month": 11,
    "index": 74.11
  },
  {
    "period": "083/12",
    "year": 83,
    "month": 12,
    "index": 73.84
  },
  {
    "period": "084/01",
    "year": 84,
    "month": 1,
    "index": 75.36
  },
  {
    "period": "084/02",
    "year": 84,
    "month": 2,
    "index": 75.04
  },
  {
    "period": "084/03",
    "year": 84,
    "month": 3,
    "index": 75.14
  },
  {
    "period": "084/04",
    "year": 84,
    "month": 4,
    "index": 76.24
  },
  {
    "period": "084/05",
    "year": 84,
    "month": 5,
    "index": 76.1
  },
  {
    "period": "084/06",
    "year": 84,
    "month": 6,
    "index": 76.92
  },
  {
    "period": "084/07",
    "year": 84,
    "month": 7,
    "index": 76.47
  },
  {
    "period": "084/08",
    "year": 84,
    "month": 8,
    "index": 76.67
  },
  {
    "period": "084/09",
    "year": 84,
    "month": 9,
    "index": 77.13
  },
  {
    "period": "084/10",
    "year": 84,
    "month": 10,
    "index": 76.93
  },
  {
    "period": "084/11",
    "year": 84,
    "month": 11,
    "index": 77.24
  },
  {
    "period": "084/12",
    "year": 84,
    "month": 12,
    "index": 77.21
  },
  {
    "period": "085/01",
    "year": 85,
    "month": 1,
    "index": 77.09
  },
  {
    "period": "085/02",
    "year": 85,
    "month": 2,
    "index": 77.85
  },
  {
    "period": "085/03",
    "year": 85,
    "month": 3,
    "index": 77.4
  },
  {
    "period": "085/04",
    "year": 85,
    "month": 4,
    "index": 78.39
  },
  {
    "period": "085/05",
    "year": 85,
    "month": 5,
    "index": 78.3
  },
  {
    "period": "085/06",
    "year": 85,
    "month": 6,
    "index": 78.76
  },
  {
    "period": "085/07",
    "year": 85,
    "month": 7,
    "index": 77.59
  },
  {
    "period": "085/08",
    "year": 85,
    "month": 8,
    "index": 80.54
  },
  {
    "period": "085/09",
    "year": 85,
    "month": 9,
    "index": 80.09
  },
  {
    "period": "085/10",
    "year": 85,
    "month": 10,
    "index": 79.77
  },
  {
    "period": "085/11",
    "year": 85,
    "month": 11,
    "index": 79.71
  },
  {
    "period": "085/12",
    "year": 85,
    "month": 12,
    "index": 79.16
  },
  {
    "period": "086/01",
    "year": 86,
    "month": 1,
    "index": 78.61
  },
  {
    "period": "086/02",
    "year": 86,
    "month": 2,
    "index": 79.46
  },
  {
    "period": "086/03",
    "year": 86,
    "month": 3,
    "index": 78.25
  },
  {
    "period": "086/04",
    "year": 86,
    "month": 4,
    "index": 78.78
  },
  {
    "period": "086/05",
    "year": 86,
    "month": 5,
    "index": 78.89
  },
  {
    "period": "086/06",
    "year": 86,
    "month": 6,
    "index": 80.2
  },
  {
    "period": "086/07",
    "year": 86,
    "month": 7,
    "index": 80.16
  },
  {
    "period": "086/08",
    "year": 86,
    "month": 8,
    "index": 80.07
  },
  {
    "period": "086/09",
    "year": 86,
    "month": 9,
    "index": 80.6
  },
  {
    "period": "086/10",
    "year": 86,
    "month": 10,
    "index": 79.51
  },
  {
    "period": "086/11",
    "year": 86,
    "month": 11,
    "index": 79.3
  },
  {
    "period": "086/12",
    "year": 86,
    "month": 12,
    "index": 79.37
  },
  {
    "period": "087/01",
    "year": 87,
    "month": 1,
    "index": 80.18
  },
  {
    "period": "087/02",
    "year": 87,
    "month": 2,
    "index": 79.69
  },
  {
    "period": "087/03",
    "year": 87,
    "month": 3,
    "index": 80.18
  },
  {
    "period": "087/04",
    "year": 87,
    "month": 4,
    "index": 80.45
  },
  {
    "period": "087/05",
    "year": 87,
    "month": 5,
    "index": 80.2
  },
  {
    "period": "087/06",
    "year": 87,
    "month": 6,
    "index": 81.36
  },
  {
    "period": "087/07",
    "year": 87,
    "month": 7,
    "index": 80.83
  },
  {
    "period": "087/08",
    "year": 87,
    "month": 8,
    "index": 80.43
  },
  {
    "period": "087/09",
    "year": 87,
    "month": 9,
    "index": 80.92
  },
  {
    "period": "087/10",
    "year": 87,
    "month": 10,
    "index": 81.56
  },
  {
    "period": "087/11",
    "year": 87,
    "month": 11,
    "index": 82.4
  },
  {
    "period": "087/12",
    "year": 87,
    "month": 12,
    "index": 81.05
  },
  {
    "period": "088/01",
    "year": 88,
    "month": 1,
    "index": 80.5
  },
  {
    "period": "088/02",
    "year": 88,
    "month": 2,
    "index": 81.36
  },
  {
    "period": "088/03",
    "year": 88,
    "month": 3,
    "index": 79.81
  },
  {
    "period": "088/04",
    "year": 88,
    "month": 4,
    "index": 80.38
  },
  {
    "period": "088/05",
    "year": 88,
    "month": 5,
    "index": 80.6
  },
  {
    "period": "088/06",
    "year": 88,
    "month": 6,
    "index": 80.67
  },
  {
    "period": "088/07",
    "year": 88,
    "month": 7,
    "index": 80.16
  },
  {
    "period": "088/08",
    "year": 88,
    "month": 8,
    "index": 81.35
  },
  {
    "period": "088/09",
    "year": 88,
    "month": 9,
    "index": 81.39
  },
  {
    "period": "088/10",
    "year": 88,
    "month": 10,
    "index": 81.9
  },
  {
    "period": "088/11",
    "year": 88,
    "month": 11,
    "index": 81.66
  },
  {
    "period": "088/12",
    "year": 88,
    "month": 12,
    "index": 81.17
  },
  {
    "period": "089/01",
    "year": 89,
    "month": 1,
    "index": 80.91
  },
  {
    "period": "089/02",
    "year": 89,
    "month": 2,
    "index": 82.11
  },
  {
    "period": "089/03",
    "year": 89,
    "month": 3,
    "index": 80.7
  },
  {
    "period": "089/04",
    "year": 89,
    "month": 4,
    "index": 81.37
  },
  {
    "period": "089/05",
    "year": 89,
    "month": 5,
    "index": 81.88
  },
  {
    "period": "089/06",
    "year": 89,
    "month": 6,
    "index": 81.77
  },
  {
    "period": "089/07",
    "year": 89,
    "month": 7,
    "index": 81.32
  },
  {
    "period": "089/08",
    "year": 89,
    "month": 8,
    "index": 81.57
  },
  {
    "period": "089/09",
    "year": 89,
    "month": 9,
    "index": 82.71
  },
  {
    "period": "089/10",
    "year": 89,
    "month": 10,
    "index": 82.73
  },
  {
    "period": "089/11",
    "year": 89,
    "month": 11,
    "index": 83.5
  },
  {
    "period": "089/12",
    "year": 89,
    "month": 12,
    "index": 82.5
  },
  {
    "period": "090/01",
    "year": 90,
    "month": 1,
    "index": 82.82
  },
  {
    "period": "090/02",
    "year": 90,
    "month": 2,
    "index": 81.27
  },
  {
    "period": "090/03",
    "year": 90,
    "month": 3,
    "index": 81.05
  },
  {
    "period": "090/04",
    "year": 90,
    "month": 4,
    "index": 81.72
  },
  {
    "period": "090/05",
    "year": 90,
    "month": 5,
    "index": 81.7
  },
  {
    "period": "090/06",
    "year": 90,
    "month": 6,
    "index": 81.65
  },
  {
    "period": "090/07",
    "year": 90,
    "month": 7,
    "index": 81.4
  },
  {
    "period": "090/08",
    "year": 90,
    "month": 8,
    "index": 81.94
  },
  {
    "period": "090/09",
    "year": 90,
    "month": 9,
    "index": 82.29
  },
  {
    "period": "090/10",
    "year": 90,
    "month": 10,
    "index": 83.54
  },
  {
    "period": "090/11",
    "year": 90,
    "month": 11,
    "index": 82.55
  },
  {
    "period": "090/12",
    "year": 90,
    "month": 12,
    "index": 81.11
  },
  {
    "period": "091/01",
    "year": 91,
    "month": 1,
    "index": 81.43
  },
  {
    "period": "091/02",
    "year": 91,
    "month": 2,
    "index": 82.42
  },
  {
    "period": "091/03",
    "year": 91,
    "month": 3,
    "index": 81.06
  },
  {
    "period": "091/04",
    "year": 91,
    "month": 4,
    "index": 81.89
  },
  {
    "period": "091/05",
    "year": 91,
    "month": 5,
    "index": 81.49
  },
  {
    "period": "091/06",
    "year": 91,
    "month": 6,
    "index": 81.74
  },
  {
    "period": "091/07",
    "year": 91,
    "month": 7,
    "index": 81.75
  },
  {
    "period": "091/08",
    "year": 91,
    "month": 8,
    "index": 81.72
  },
  {
    "period": "091/09",
    "year": 91,
    "month": 9,
    "index": 81.66
  },
  {
    "period": "091/10",
    "year": 91,
    "month": 10,
    "index": 82.12
  },
  {
    "period": "091/11",
    "year": 91,
    "month": 11,
    "index": 82.09
  },
  {
    "period": "091/12",
    "year": 91,
    "month": 12,
    "index": 81.74
  },
  {
    "period": "092/01",
    "year": 92,
    "month": 1,
    "index": 82.31
  },
  {
    "period": "092/02",
    "year": 92,
    "month": 2,
    "index": 81.17
  },
  {
    "period": "092/03",
    "year": 92,
    "month": 3,
    "index": 80.91
  },
  {
    "period": "092/04",
    "year": 92,
    "month": 4,
    "index": 81.79
  },
  {
    "period": "092/05",
    "year": 92,
    "month": 5,
    "index": 81.75
  },
  {
    "period": "092/06",
    "year": 92,
    "month": 6,
    "index": 81.28
  },
  {
    "period": "092/07",
    "year": 92,
    "month": 7,
    "index": 80.94
  },
  {
    "period": "092/08",
    "year": 92,
    "month": 8,
    "index": 81.24
  },
  {
    "period": "092/09",
    "year": 92,
    "month": 9,
    "index": 81.49
  },
  {
    "period": "092/10",
    "year": 92,
    "month": 10,
    "index": 82.07
  },
  {
    "period": "092/11",
    "year": 92,
    "month": 11,
    "index": 81.71
  },
  {
    "period": "092/12",
    "year": 92,
    "month": 12,
    "index": 81.69
  },
  {
    "period": "093/01",
    "year": 93,
    "month": 1,
    "index": 82.32
  },
  {
    "period": "093/02",
    "year": 93,
    "month": 2,
    "index": 81.69
  },
  {
    "period": "093/03",
    "year": 93,
    "month": 3,
    "index": 81.63
  },
  {
    "period": "093/04",
    "year": 93,
    "month": 4,
    "index": 82.57
  },
  {
    "period": "093/05",
    "year": 93,
    "month": 5,
    "index": 82.49
  },
  {
    "period": "093/06",
    "year": 93,
    "month": 6,
    "index": 82.69
  },
  {
    "period": "093/07",
    "year": 93,
    "month": 7,
    "index": 83.63
  },
  {
    "period": "093/08",
    "year": 93,
    "month": 8,
    "index": 83.31
  },
  {
    "period": "093/09",
    "year": 93,
    "month": 9,
    "index": 83.76
  },
  {
    "period": "093/10",
    "year": 93,
    "month": 10,
    "index": 84.03
  },
  {
    "period": "093/11",
    "year": 93,
    "month": 11,
    "index": 82.95
  },
  {
    "period": "093/12",
    "year": 93,
    "month": 12,
    "index": 83.01
  },
  {
    "period": "094/01",
    "year": 94,
    "month": 1,
    "index": 82.72
  },
  {
    "period": "094/02",
    "year": 94,
    "month": 2,
    "index": 83.27
  },
  {
    "period": "094/03",
    "year": 94,
    "month": 3,
    "index": 83.51
  },
  {
    "period": "094/04",
    "year": 94,
    "month": 4,
    "index": 83.93
  },
  {
    "period": "094/05",
    "year": 94,
    "month": 5,
    "index": 84.39
  },
  {
    "period": "094/06",
    "year": 94,
    "month": 6,
    "index": 84.66
  },
  {
    "period": "094/07",
    "year": 94,
    "month": 7,
    "index": 85.65
  },
  {
    "period": "094/08",
    "year": 94,
    "month": 8,
    "index": 86.28
  },
  {
    "period": "094/09",
    "year": 94,
    "month": 9,
    "index": 86.41
  },
  {
    "period": "094/10",
    "year": 94,
    "month": 10,
    "index": 86.34
  },
  {
    "period": "094/11",
    "year": 94,
    "month": 11,
    "index": 85.03
  },
  {
    "period": "094/12",
    "year": 94,
    "month": 12,
    "index": 84.84
  },
  {
    "period": "095/01",
    "year": 95,
    "month": 1,
    "index": 84.94
  },
  {
    "period": "095/02",
    "year": 95,
    "month": 2,
    "index": 84.09
  },
  {
    "period": "095/03",
    "year": 95,
    "month": 3,
    "index": 83.86
  },
  {
    "period": "095/04",
    "year": 95,
    "month": 4,
    "index": 84.96
  },
  {
    "period": "095/05",
    "year": 95,
    "month": 5,
    "index": 85.73
  },
  {
    "period": "095/06",
    "year": 95,
    "month": 6,
    "index": 86.13
  },
  {
    "period": "095/07",
    "year": 95,
    "month": 7,
    "index": 86.32
  },
  {
    "period": "095/08",
    "year": 95,
    "month": 8,
    "index": 85.8
  },
  {
    "period": "095/09",
    "year": 95,
    "month": 9,
    "index": 85.33
  },
  {
    "period": "095/10",
    "year": 95,
    "month": 10,
    "index": 85.31
  },
  {
    "period": "095/11",
    "year": 95,
    "month": 11,
    "index": 85.24
  },
  {
    "period": "095/12",
    "year": 95,
    "month": 12,
    "index": 85.42
  },
  {
    "period": "096/01",
    "year": 96,
    "month": 1,
    "index": 85.24
  },
  {
    "period": "096/02",
    "year": 96,
    "month": 2,
    "index": 85.56
  },
  {
    "period": "096/03",
    "year": 96,
    "month": 3,
    "index": 84.56
  },
  {
    "period": "096/04",
    "year": 96,
    "month": 4,
    "index": 85.54
  },
  {
    "period": "096/05",
    "year": 96,
    "month": 5,
    "index": 85.71
  },
  {
    "period": "096/06",
    "year": 96,
    "month": 6,
    "index": 86.24
  },
  {
    "period": "096/07",
    "year": 96,
    "month": 7,
    "index": 86.04
  },
  {
    "period": "096/08",
    "year": 96,
    "month": 8,
    "index": 87.18
  },
  {
    "period": "096/09",
    "year": 96,
    "month": 9,
    "index": 87.99
  },
  {
    "period": "096/10",
    "year": 96,
    "month": 10,
    "index": 89.86
  },
  {
    "period": "096/11",
    "year": 96,
    "month": 11,
    "index": 89.33
  },
  {
    "period": "096/12",
    "year": 96,
    "month": 12,
    "index": 88.26
  },
  {
    "period": "097/01",
    "year": 97,
    "month": 1,
    "index": 87.75
  },
  {
    "period": "097/02",
    "year": 97,
    "month": 2,
    "index": 88.87
  },
  {
    "period": "097/03",
    "year": 97,
    "month": 3,
    "index": 87.91
  },
  {
    "period": "097/04",
    "year": 97,
    "month": 4,
    "index": 88.86
  },
  {
    "period": "097/05",
    "year": 97,
    "month": 5,
    "index": 88.9
  },
  {
    "period": "097/06",
    "year": 97,
    "month": 6,
    "index": 90.53
  },
  {
    "period": "097/07",
    "year": 97,
    "month": 7,
    "index": 91.04
  },
  {
    "period": "097/08",
    "year": 97,
    "month": 8,
    "index": 91.27
  },
  {
    "period": "097/09",
    "year": 97,
    "month": 9,
    "index": 90.72
  },
  {
    "period": "097/10",
    "year": 97,
    "month": 10,
    "index": 92
  },
  {
    "period": "097/11",
    "year": 97,
    "month": 11,
    "index": 91.05
  },
  {
    "period": "097/12",
    "year": 97,
    "month": 12,
    "index": 89.38
  },
  {
    "period": "098/01",
    "year": 98,
    "month": 1,
    "index": 89.04
  },
  {
    "period": "098/02",
    "year": 98,
    "month": 2,
    "index": 87.68
  },
  {
    "period": "098/03",
    "year": 98,
    "month": 3,
    "index": 87.78
  },
  {
    "period": "098/04",
    "year": 98,
    "month": 4,
    "index": 88.45
  },
  {
    "period": "098/05",
    "year": 98,
    "month": 5,
    "index": 88.82
  },
  {
    "period": "098/06",
    "year": 98,
    "month": 6,
    "index": 88.73
  },
  {
    "period": "098/07",
    "year": 98,
    "month": 7,
    "index": 88.91
  },
  {
    "period": "098/08",
    "year": 98,
    "month": 8,
    "index": 90.52
  },
  {
    "period": "098/09",
    "year": 98,
    "month": 9,
    "index": 89.91
  },
  {
    "period": "098/10",
    "year": 98,
    "month": 10,
    "index": 90.26
  },
  {
    "period": "098/11",
    "year": 98,
    "month": 11,
    "index": 89.59
  },
  {
    "period": "098/12",
    "year": 98,
    "month": 12,
    "index": 89.16
  },
  {
    "period": "099/01",
    "year": 99,
    "month": 1,
    "index": 89.27
  },
  {
    "period": "099/02",
    "year": 99,
    "month": 2,
    "index": 89.74
  },
  {
    "period": "099/03",
    "year": 99,
    "month": 3,
    "index": 88.89
  },
  {
    "period": "099/04",
    "year": 99,
    "month": 4,
    "index": 89.64
  },
  {
    "period": "099/05",
    "year": 99,
    "month": 5,
    "index": 89.49
  },
  {
    "period": "099/06",
    "year": 99,
    "month": 6,
    "index": 89.8
  },
  {
    "period": "099/07",
    "year": 99,
    "month": 7,
    "index": 90.08
  },
  {
    "period": "099/08",
    "year": 99,
    "month": 8,
    "index": 90.09
  },
  {
    "period": "099/09",
    "year": 99,
    "month": 9,
    "index": 90.18
  },
  {
    "period": "099/10",
    "year": 99,
    "month": 10,
    "index": 90.78
  },
  {
    "period": "099/11",
    "year": 99,
    "month": 11,
    "index": 90.95
  },
  {
    "period": "099/12",
    "year": 99,
    "month": 12,
    "index": 90.26
  },
  {
    "period": "100/01",
    "year": 100,
    "month": 1,
    "index": 90.25
  },
  {
    "period": "100/02",
    "year": 100,
    "month": 2,
    "index": 90.93
  },
  {
    "period": "100/03",
    "year": 100,
    "month": 3,
    "index": 90.13
  },
  {
    "period": "100/04",
    "year": 100,
    "month": 4,
    "index": 90.8
  },
  {
    "period": "100/05",
    "year": 100,
    "month": 5,
    "index": 90.98
  },
  {
    "period": "100/06",
    "year": 100,
    "month": 6,
    "index": 91.54
  },
  {
    "period": "100/07",
    "year": 100,
    "month": 7,
    "index": 91.27
  },
  {
    "period": "100/08",
    "year": 100,
    "month": 8,
    "index": 91.3
  },
  {
    "period": "100/09",
    "year": 100,
    "month": 9,
    "index": 91.42
  },
  {
    "period": "100/10",
    "year": 100,
    "month": 10,
    "index": 91.91
  },
  {
    "period": "100/11",
    "year": 100,
    "month": 11,
    "index": 91.89
  },
  {
    "period": "100/12",
    "year": 100,
    "month": 12,
    "index": 92.09
  },
  {
    "period": "101/01",
    "year": 101,
    "month": 1,
    "index": 92.38
  },
  {
    "period": "101/02",
    "year": 101,
    "month": 2,
    "index": 91.15
  },
  {
    "period": "101/03",
    "year": 101,
    "month": 3,
    "index": 91.27
  },
  {
    "period": "101/04",
    "year": 101,
    "month": 4,
    "index": 92.11
  },
  {
    "period": "101/05",
    "year": 101,
    "month": 5,
    "index": 92.57
  },
  {
    "period": "101/06",
    "year": 101,
    "month": 6,
    "index": 93.16
  },
  {
    "period": "101/07",
    "year": 101,
    "month": 7,
    "index": 93.52
  },
  {
    "period": "101/08",
    "year": 101,
    "month": 8,
    "index": 94.43
  },
  {
    "period": "101/09",
    "year": 101,
    "month": 9,
    "index": 94.12
  },
  {
    "period": "101/10",
    "year": 101,
    "month": 10,
    "index": 94.05
  },
  {
    "period": "101/11",
    "year": 101,
    "month": 11,
    "index": 93.35
  },
  {
    "period": "101/12",
    "year": 101,
    "month": 12,
    "index": 93.58
  },
  {
    "period": "102/01",
    "year": 102,
    "month": 1,
    "index": 93.41
  },
  {
    "period": "102/02",
    "year": 102,
    "month": 2,
    "index": 93.85
  },
  {
    "period": "102/03",
    "year": 102,
    "month": 3,
    "index": 92.5
  },
  {
    "period": "102/04",
    "year": 102,
    "month": 4,
    "index": 93.08
  },
  {
    "period": "102/05",
    "year": 102,
    "month": 5,
    "index": 93.25
  },
  {
    "period": "102/06",
    "year": 102,
    "month": 6,
    "index": 93.72
  },
  {
    "period": "102/07",
    "year": 102,
    "month": 7,
    "index": 93.58
  },
  {
    "period": "102/08",
    "year": 102,
    "month": 8,
    "index": 93.69
  },
  {
    "period": "102/09",
    "year": 102,
    "month": 9,
    "index": 94.92
  },
  {
    "period": "102/10",
    "year": 102,
    "month": 10,
    "index": 94.66
  },
  {
    "period": "102/11",
    "year": 102,
    "month": 11,
    "index": 93.98
  },
  {
    "period": "102/12",
    "year": 102,
    "month": 12,
    "index": 93.89
  },
  {
    "period": "103/01",
    "year": 103,
    "month": 1,
    "index": 94.18
  },
  {
    "period": "103/02",
    "year": 103,
    "month": 2,
    "index": 93.81
  },
  {
    "period": "103/03",
    "year": 103,
    "month": 3,
    "index": 93.99
  },
  {
    "period": "103/04",
    "year": 103,
    "month": 4,
    "index": 94.62
  },
  {
    "period": "103/05",
    "year": 103,
    "month": 5,
    "index": 94.76
  },
  {
    "period": "103/06",
    "year": 103,
    "month": 6,
    "index": 95.25
  },
  {
    "period": "103/07",
    "year": 103,
    "month": 7,
    "index": 95.22
  },
  {
    "period": "103/08",
    "year": 103,
    "month": 8,
    "index": 95.64
  },
  {
    "period": "103/09",
    "year": 103,
    "month": 9,
    "index": 95.59
  },
  {
    "period": "103/10",
    "year": 103,
    "month": 10,
    "index": 95.66
  },
  {
    "period": "103/11",
    "year": 103,
    "month": 11,
    "index": 94.78
  },
  {
    "period": "103/12",
    "year": 103,
    "month": 12,
    "index": 94.46
  },
  {
    "period": "104/01",
    "year": 104,
    "month": 1,
    "index": 93.3
  },
  {
    "period": "104/02",
    "year": 104,
    "month": 2,
    "index": 93.62
  },
  {
    "period": "104/03",
    "year": 104,
    "month": 3,
    "index": 93.41
  },
  {
    "period": "104/04",
    "year": 104,
    "month": 4,
    "index": 93.84
  },
  {
    "period": "104/05",
    "year": 104,
    "month": 5,
    "index": 94.07
  },
  {
    "period": "104/06",
    "year": 104,
    "month": 6,
    "index": 94.72
  },
  {
    "period": "104/07",
    "year": 104,
    "month": 7,
    "index": 94.62
  },
  {
    "period": "104/08",
    "year": 104,
    "month": 8,
    "index": 95.21
  },
  {
    "period": "104/09",
    "year": 104,
    "month": 9,
    "index": 95.87
  },
  {
    "period": "104/10",
    "year": 104,
    "month": 10,
    "index": 95.95
  },
  {
    "period": "104/11",
    "year": 104,
    "month": 11,
    "index": 95.29
  },
  {
    "period": "104/12",
    "year": 104,
    "month": 12,
    "index": 94.58
  },
  {
    "period": "105/01",
    "year": 105,
    "month": 1,
    "index": 94.05
  },
  {
    "period": "105/02",
    "year": 105,
    "month": 2,
    "index": 95.88
  },
  {
    "period": "105/03",
    "year": 105,
    "month": 3,
    "index": 95.29
  },
  {
    "period": "105/04",
    "year": 105,
    "month": 4,
    "index": 95.6
  },
  {
    "period": "105/05",
    "year": 105,
    "month": 5,
    "index": 95.23
  },
  {
    "period": "105/06",
    "year": 105,
    "month": 6,
    "index": 95.57
  },
  {
    "period": "105/07",
    "year": 105,
    "month": 7,
    "index": 95.79
  },
  {
    "period": "105/08",
    "year": 105,
    "month": 8,
    "index": 95.75
  },
  {
    "period": "105/09",
    "year": 105,
    "month": 9,
    "index": 96.19
  },
  {
    "period": "105/10",
    "year": 105,
    "month": 10,
    "index": 97.58
  },
  {
    "period": "105/11",
    "year": 105,
    "month": 11,
    "index": 97.17
  },
  {
    "period": "105/12",
    "year": 105,
    "month": 12,
    "index": 96.18
  },
  {
    "period": "106/01",
    "year": 106,
    "month": 1,
    "index": 96.16
  },
  {
    "period": "106/02",
    "year": 106,
    "month": 2,
    "index": 95.82
  },
  {
    "period": "106/03",
    "year": 106,
    "month": 3,
    "index": 95.46
  },
  {
    "period": "106/04",
    "year": 106,
    "month": 4,
    "index": 95.69
  },
  {
    "period": "106/05",
    "year": 106,
    "month": 5,
    "index": 95.8
  },
  {
    "period": "106/06",
    "year": 106,
    "month": 6,
    "index": 96.53
  },
  {
    "period": "106/07",
    "year": 106,
    "month": 7,
    "index": 96.53
  },
  {
    "period": "106/08",
    "year": 106,
    "month": 8,
    "index": 96.67
  },
  {
    "period": "106/09",
    "year": 106,
    "month": 9,
    "index": 96.66
  },
  {
    "period": "106/10",
    "year": 106,
    "month": 10,
    "index": 97.26
  },
  {
    "period": "106/11",
    "year": 106,
    "month": 11,
    "index": 97.5
  },
  {
    "period": "106/12",
    "year": 106,
    "month": 12,
    "index": 97.35
  },
  {
    "period": "107/01",
    "year": 107,
    "month": 1,
    "index": 97.02
  },
  {
    "period": "107/02",
    "year": 107,
    "month": 2,
    "index": 97.93
  },
  {
    "period": "107/03",
    "year": 107,
    "month": 3,
    "index": 96.98
  },
  {
    "period": "107/04",
    "year": 107,
    "month": 4,
    "index": 97.61
  },
  {
    "period": "107/05",
    "year": 107,
    "month": 5,
    "index": 97.48
  },
  {
    "period": "107/06",
    "year": 107,
    "month": 6,
    "index": 97.88
  },
  {
    "period": "107/07",
    "year": 107,
    "month": 7,
    "index": 98.22
  },
  {
    "period": "107/08",
    "year": 107,
    "month": 8,
    "index": 98.16
  },
  {
    "period": "107/09",
    "year": 107,
    "month": 9,
    "index": 98.32
  },
  {
    "period": "107/10",
    "year": 107,
    "month": 10,
    "index": 98.39
  },
  {
    "period": "107/11",
    "year": 107,
    "month": 11,
    "index": 97.78
  },
  {
    "period": "107/12",
    "year": 107,
    "month": 12,
    "index": 97.29
  },
  {
    "period": "108/01",
    "year": 108,
    "month": 1,
    "index": 97.19
  },
  {
    "period": "108/02",
    "year": 108,
    "month": 2,
    "index": 98.14
  },
  {
    "period": "108/03",
    "year": 108,
    "month": 3,
    "index": 97.52
  },
  {
    "period": "108/04",
    "year": 108,
    "month": 4,
    "index": 98.25
  },
  {
    "period": "108/05",
    "year": 108,
    "month": 5,
    "index": 98.39
  },
  {
    "period": "108/06",
    "year": 108,
    "month": 6,
    "index": 98.71
  },
  {
    "period": "108/07",
    "year": 108,
    "month": 7,
    "index": 98.6
  },
  {
    "period": "108/08",
    "year": 108,
    "month": 8,
    "index": 98.58
  },
  {
    "period": "108/09",
    "year": 108,
    "month": 9,
    "index": 98.73
  },
  {
    "period": "108/10",
    "year": 108,
    "month": 10,
    "index": 98.75
  },
  {
    "period": "108/11",
    "year": 108,
    "month": 11,
    "index": 98.35
  },
  {
    "period": "108/12",
    "year": 108,
    "month": 12,
    "index": 98.41
  },
  {
    "period": "109/01",
    "year": 109,
    "month": 1,
    "index": 99
  },
  {
    "period": "109/02",
    "year": 109,
    "month": 2,
    "index": 97.94
  },
  {
    "period": "109/03",
    "year": 109,
    "month": 3,
    "index": 97.5
  },
  {
    "period": "109/04",
    "year": 109,
    "month": 4,
    "index": 97.3
  },
  {
    "period": "109/05",
    "year": 109,
    "month": 5,
    "index": 97.2
  },
  {
    "period": "109/06",
    "year": 109,
    "month": 6,
    "index": 97.98
  },
  {
    "period": "109/07",
    "year": 109,
    "month": 7,
    "index": 98.1
  },
  {
    "period": "109/08",
    "year": 109,
    "month": 8,
    "index": 98.25
  },
  {
    "period": "109/09",
    "year": 109,
    "month": 9,
    "index": 98.16
  },
  {
    "period": "109/10",
    "year": 109,
    "month": 10,
    "index": 98.49
  },
  {
    "period": "109/11",
    "year": 109,
    "month": 11,
    "index": 98.44
  },
  {
    "period": "109/12",
    "year": 109,
    "month": 12,
    "index": 98.45
  },
  {
    "period": "110/01",
    "year": 110,
    "month": 1,
    "index": 98.81
  },
  {
    "period": "110/02",
    "year": 110,
    "month": 2,
    "index": 99.29
  },
  {
    "period": "110/03",
    "year": 110,
    "month": 3,
    "index": 98.69
  },
  {
    "period": "110/04",
    "year": 110,
    "month": 4,
    "index": 99.35
  },
  {
    "period": "110/05",
    "year": 110,
    "month": 5,
    "index": 99.58
  },
  {
    "period": "110/06",
    "year": 110,
    "month": 6,
    "index": 99.77
  },
  {
    "period": "110/07",
    "year": 110,
    "month": 7,
    "index": 99.97
  },
  {
    "period": "110/08",
    "year": 110,
    "month": 8,
    "index": 100.55
  },
  {
    "period": "110/09",
    "year": 110,
    "month": 9,
    "index": 100.71
  },
  {
    "period": "110/10",
    "year": 110,
    "month": 10,
    "index": 101
  },
  {
    "period": "110/11",
    "year": 110,
    "month": 11,
    "index": 101.24
  },
  {
    "period": "110/12",
    "year": 110,
    "month": 12,
    "index": 101.04
  },
  {
    "period": "111/01",
    "year": 111,
    "month": 1,
    "index": 101.61
  },
  {
    "period": "111/02",
    "year": 111,
    "month": 2,
    "index": 101.6
  },
  {
    "period": "111/03",
    "year": 111,
    "month": 3,
    "index": 101.92
  },
  {
    "period": "111/04",
    "year": 111,
    "month": 4,
    "index": 102.7
  },
  {
    "period": "111/05",
    "year": 111,
    "month": 5,
    "index": 102.96
  },
  {
    "period": "111/06",
    "year": 111,
    "month": 6,
    "index": 103.35
  },
  {
    "period": "111/07",
    "year": 111,
    "month": 7,
    "index": 103.32
  },
  {
    "period": "111/08",
    "year": 111,
    "month": 8,
    "index": 103.24
  },
  {
    "period": "111/09",
    "year": 111,
    "month": 9,
    "index": 103.49
  },
  {
    "period": "111/10",
    "year": 111,
    "month": 10,
    "index": 103.77
  },
  {
    "period": "111/11",
    "year": 111,
    "month": 11,
    "index": 103.62
  },
  {
    "period": "111/12",
    "year": 111,
    "month": 12,
    "index": 103.78
  },
  {
    "period": "112/01",
    "year": 112,
    "month": 1,
    "index": 104.71
  },
  {
    "period": "112/02",
    "year": 112,
    "month": 2,
    "index": 104.06
  },
  {
    "period": "112/03",
    "year": 112,
    "month": 3,
    "index": 104.32
  },
  {
    "period": "112/04",
    "year": 112,
    "month": 4,
    "index": 105.11
  },
  {
    "period": "112/05",
    "year": 112,
    "month": 5,
    "index": 105.04
  },
  {
    "period": "112/06",
    "year": 112,
    "month": 6,
    "index": 105.16
  },
  {
    "period": "112/07",
    "year": 112,
    "month": 7,
    "index": 105.26
  },
  {
    "period": "112/08",
    "year": 112,
    "month": 8,
    "index": 105.85
  },
  {
    "period": "112/09",
    "year": 112,
    "month": 9,
    "index": 106.52
  },
  {
    "period": "112/10",
    "year": 112,
    "month": 10,
    "index": 106.92
  },
  {
    "period": "112/11",
    "year": 112,
    "month": 11,
    "index": 106.62
  },
  {
    "period": "112/12",
    "year": 112,
    "month": 12,
    "index": 106.58
  },
  {
    "period": "113/01",
    "year": 113,
    "month": 1,
    "index": 106.59
  },
  {
    "period": "113/02",
    "year": 113,
    "month": 2,
    "index": 107.26
  },
  {
    "period": "113/03",
    "year": 113,
    "month": 3,
    "index": 106.56
  },
  {
    "period": "113/04",
    "year": 113,
    "month": 4,
    "index": 107.15
  },
  {
    "period": "113/05",
    "year": 113,
    "month": 5,
    "index": 107.38
  },
  {
    "period": "113/06",
    "year": 113,
    "month": 6,
    "index": 107.71
  },
  {
    "period": "113/07",
    "year": 113,
    "month": 7,
    "index": 107.92
  },
  {
    "period": "113/08",
    "year": 113,
    "month": 8,
    "index": 108.34
  },
  {
    "period": "113/09",
    "year": 113,
    "month": 9,
    "index": 108.46
  },
  {
    "period": "113/10",
    "year": 113,
    "month": 10,
    "index": 108.73
  },
  {
    "period": "113/11",
    "year": 113,
    "month": 11,
    "index": 108.84
  },
  {
    "period": "113/12",
    "year": 113,
    "month": 12,
    "index": 108.82
  },
  {
    "period": "114/01",
    "year": 114,
    "month": 1,
    "index": 109.44
  },
  {
    "period": "114/02",
    "year": 114,
    "month": 2,
    "index": 109
  },
  {
    "period": "114/03",
    "year": 114,
    "month": 3,
    "index": 109.05
  },
  {
    "period": "114/04",
    "year": 114,
    "month": 4,
    "index": 109.33
  },
  {
    "period": "114/05",
    "year": 114,
    "month": 5,
    "index": 109.03
  },
  {
    "period": "114/06",
    "year": 114,
    "month": 6,
    "index": 109.17
  },
  {
    "period": "114/07",
    "year": 114,
    "month": 7,
    "index": 109.57
  },
  {
    "period": "114/08",
    "year": 114,
    "month": 8,
    "index": 110.07
  },
  {
    "period": "114/09",
    "year": 114,
    "month": 9,
    "index": 109.82
  },
  {
    "period": "114/10",
    "year": 114,
    "month": 10,
    "index": 110.33
  },
  {
    "period": "114/11",
    "year": 114,
    "month": 11,
    "index": 110.16
  },
  {
    "period": "114/12",
    "year": 114,
    "month": 12,
    "index": 110.24
  },
  {
    "period": "115/01",
    "year": 115,
    "month": 1,
    "index": 110.22
  },
  {
    "period": "115/02",
    "year": 115,
    "month": 2,
    "index": 110.91
  },
  {
    "period": "115/03",
    "year": 115,
    "month": 3,
    "index": 110.36
  },
  {
    "period": "115/04",
    "year": 115,
    "month": 4,
    "index": 111.23
  }
];

export default LAND_VALUE_TAX_CPI_DATA;
